<template>
  <div class="cb-page import-wizard"><div class="wizard-shell">
    <header class="wizard-header"><v-btn variant="text" prepend-icon="mdi-arrow-left" @click="backToPanel">Voltar</v-btn><div><p class="eyebrow">Importação da competência</p><h1>{{ competenceLabel }}</h1></div><v-chip size="small" variant="tonal">Etapa {{ step }} de 4</v-chip></header>
    <v-progress-linear :model-value="step*25" color="primary" height="6" rounded aria-label="Progresso da importação" />
    <alert-strip v-if="errorMessage" variant="info" :description="errorMessage" />
    <main class="wizard-card cb-card">
      <div v-if="loading" class="wizard-state" role="status"><v-progress-circular indeterminate /><p>Carregando revisão…</p></div>
      <template v-else-if="published">
        <v-icon color="success" size="52">mdi-check-circle-outline</v-icon><h2>Lote publicado</h2><p>As fontes foram publicadas juntas e agora estão disponíveis para o próximo gate do fechamento.</p><dl class="summary"><div><dt>Fontes</dt><dd>{{ publication?.sourceCount ?? review?.selectedSourceCount }}</dd></div><div><dt>Itens</dt><dd>{{ publication?.itemCount ?? totalCandidates }}</dd></div></dl><v-btn color="primary" @click="backToPanel">Voltar ao painel</v-btn>
      </template>
      <template v-else-if="needsResumeIntent">
        <p class="eyebrow">Retomar com segurança</p><h2>A revisão foi preservada</h2><p>O arquivo não fica armazenado. Confirme novamente a intenção de acessar dados protegidos; se a preparação estiver incompleta, o mesmo workbook será solicitado.</p><v-checkbox v-model="sensitiveConfirmed" label="Entendo que acessarei dados protegidos desta importação" hide-details /><v-btn color="primary" :disabled="!sensitiveConfirmed" :loading="acting" @click="resumeReview">Retomar revisão</v-btn>
      </template>
      <template v-else-if="step===1">
        <p class="eyebrow">Dados de origem</p><h2>Selecione o workbook</h2><p>O arquivo permanece somente nesta sessão do navegador. A leitura identifica fontes conhecidas; ainda não cria itens financeiros.</p><v-checkbox v-model="sensitiveConfirmed" label="Entendo que acessarei dados protegidos nesta leitura" hide-details /><v-file-input v-model="workbookInput" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" label="Workbook XLSX" prepend-icon="mdi-file-excel-outline" :disabled="acting" /><v-btn color="primary" :disabled="!selectedFile||!sensitiveConfirmed" :loading="acting" @click="inventoryWorkbook">Identificar fontes</v-btn>
      </template>
      <template v-else-if="step===2">
        <p class="eyebrow">Fontes reconhecidas</p><h2>Confira o que será preparado</h2><p>{{ selectedSheets.length }} fonte(s) conhecida(s) possuem perfil compatível. Abas novas ou ambíguas ficam para revisão avançada na V32.</p><ul class="source-list"><li v-for="sheet in selectedSheets" :key="sheet.sheetName"><v-icon color="success">mdi-check-circle-outline</v-icon><div><strong>{{ sheet.sheetName }}</strong><small>{{ sheet.nonEmptyDataRows }} linha(s) materiais · {{ sheet.recommendedProfileName }}</small></div></li></ul><div v-if="reviewSheets.length" class="notice" role="status"><strong>{{ reviewSheets.length }} aba(s) precisam de revisão</strong><p>Elas não serão incluídas silenciosamente nesta publicação.</p></div><v-btn color="primary" :disabled="!selectedSheets.length||!selectedFile" :loading="acting" @click="prepareSources">Preparar fontes reconhecidas</v-btn>
      </template>
      <template v-else-if="step===3 && review?.status==='DRAFT'">
        <p class="eyebrow">Conferência</p><h2>Fontes preparadas</h2><p>O staging ainda está invisível ao cálculo. O preflight revalida versão, perfis, participantes, acesso e sobreposição.</p><dl class="summary"><div><dt>Fontes materializadas</dt><dd>{{ materializedCount }}/{{ review.selectedSourceCount }}</dd></div><div><dt>Itens preparados</dt><dd>{{ totalCandidates }}</dd></div><div><dt>Expiração do staging</dt><dd>{{ formatDate(review.stagingExpiresAt) }}</dd></div></dl><v-btn color="primary" :loading="acting" @click="runPreflight">Conferir importação</v-btn>
      </template>
      <template v-else-if="step===4 && review?.status==='PREFLIGHT_READY'">
        <p class="eyebrow">Confirmação única</p><h2>Publicar lote</h2><p>Esta confirmação cria os itens canônicos de todas as fontes em uma única transação. Não calcula, aprova nem cria obrigações.</p><dl class="summary"><div><dt>Fontes</dt><dd>{{ preflight?.sourceCount ?? review.selectedSourceCount }}</dd></div><div><dt>Itens</dt><dd>{{ preflight?.itemCount ?? totalCandidates }}</dd></div><div><dt>Total de adições</dt><dd>{{ money(preflight?.additionTotal ?? totalAdditions) }}</dd></div><div><dt>Total de reversões</dt><dd>{{ money(preflight?.reversalTotal ?? totalReversals) }}</dd></div></dl><v-checkbox v-model="financialConfirmed" label="Confirmo a publicação financeira deste lote" hide-details /><v-btn color="primary" :disabled="!financialConfirmed" :loading="acting" @click="publish">Confirmar lote</v-btn>
      </template>
    </main>
    <footer v-if="!published" class="sticky-action"><span>{{ stepHint }}</span><v-btn variant="text" @click="backToPanel">Salvar e sair</v-btn></footer>
  </div></div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AlertStrip from '@/components/AlertStrip.vue'
import FinancialClosingService,{type FinancialClosing,type WorkbookInventory,type WorkbookPreflight,type WorkbookPublication,type WorkbookReview,type WorkbookSheetInventory} from '@/services/FinancialClosingService'

const route=useRoute(),router=useRouter();const closing=ref<FinancialClosing|null>(null),review=ref<WorkbookReview|null>(null),inventory=ref<WorkbookInventory|null>(null),preflight=ref<WorkbookPreflight|null>(null),publication=ref<WorkbookPublication|null>(null),workbookInput=ref<File|File[]|null>(null),loading=ref(true),acting=ref(false),errorMessage=ref(''),sensitiveConfirmed=ref(false),financialConfirmed=ref(false),resumed=ref(false);
const routeReviewId=computed(()=>String(route.params.reviewId||'nova'));const selectedFile=computed(()=>Array.isArray(workbookInput.value)?workbookInput.value[0]||null:workbookInput.value);const selectedSheets=computed(()=>inventory.value?.sheets.filter(sheet=>sheet.selectionStatus==='AUTO_SELECTED'&&sheet.recommendedProfileId)||[]);const reviewSheets=computed(()=>inventory.value?.sheets.filter(sheet=>sheet.selectionStatus==='REVIEW_REQUIRED')||[]);
const published=computed(()=>review.value?.status==='PUBLISHED'||Boolean(publication.value));const needsResumeIntent=computed(()=>routeReviewId.value!=='nova'&&!published.value&&!resumed.value);const materializedCount=computed(()=>review.value?.sources.filter(source=>['MATERIALIZED','PUBLISHED'].includes(source.status)).length||0);const totalCandidates=computed(()=>review.value?.sources.reduce((sum,source)=>sum+source.candidateCount,0)||0);const totalAdditions=computed(()=>review.value?.sources.reduce((sum,source)=>sum+source.additionTotal,0)||0);const totalReversals=computed(()=>review.value?.sources.reduce((sum,source)=>sum+source.reversalTotal,0)||0);
const step=computed(()=>published.value?4:review.value?.status==='PREFLIGHT_READY'?4:review.value?3:inventory.value?2:1);const competenceLabel=computed(()=>closing.value?`${String(closing.value.periodMonth).padStart(2,'0')}/${closing.value.periodYear} · ${closing.value.closingKey}`:'Apuração');const stepHint=computed(()=>['','Selecione o arquivo uma vez nesta sessão.','Somente fontes reconhecidas avançam.','O staging ainda não afeta o cálculo.','A publicação é atômica e idempotente.'][step.value]);
async function initialize(){loading.value=true;try{const all=(await FinancialClosingService.list()).data;closing.value=all.find(item=>item.id===String(route.params.closingId))||null;if(!closing.value)throw new Error('missing closing');if(routeReviewId.value!=='nova'){const progress=(await FinancialClosingService.workbookReviewProgress(closing.value.id,routeReviewId.value)).data;if(progress.status==='PUBLISHED'){review.value={...progress,preflightHmac:null,sources:[]} as WorkbookReview;resumed.value=true}}}catch{errorMessage.value='Não foi possível abrir esta revisão no workspace atual.'}finally{loading.value=false}}
async function resumeReview(){if(!closing.value)return;acting.value=true;errorMessage.value='';try{await FinancialClosingService.confirmWorkbookSensitiveIntent(closing.value.id,routeReviewId.value);review.value=(await FinancialClosingService.workbookReview(closing.value.id,routeReviewId.value)).data;resumed.value=true}catch{errorMessage.value='O acesso expirou, foi revogado ou a revisão não está mais disponível.'}finally{acting.value=false}}
async function inventoryWorkbook(){if(!closing.value||!selectedFile.value)return;acting.value=true;errorMessage.value='';try{inventory.value=(await FinancialClosingService.workbookInventory(closing.value,selectedFile.value,true)).data;if(!selectedSheets.value.length)errorMessage.value='Nenhuma fonte reconhecida está pronta. Use a operação anterior para configurar perfis; a resolução guiada completa chega na V32.'}catch{errorMessage.value='Não foi possível ler o workbook. O arquivo não foi armazenado.'}finally{acting.value=false}}
async function prepareSources(){if(!closing.value||!selectedFile.value)return;acting.value=true;errorMessage.value='';try{const expected=routeReviewId.value==='nova'?undefined:routeReviewId.value;review.value=(await FinancialClosingService.prepareWorkbookReview(closing.value,selectedFile.value,selectedSheets.value.map(sheet=>sheet.recommendedProfileId!),expected)).data;resumed.value=true;await router.replace({name:'closing-import-wizard',params:{closingId:closing.value.id,reviewId:review.value.id}})}catch(error:any){errorMessage.value=error?.response?.status===409?'Este arquivo não corresponde à revisão retomada. Volte ao painel e inicie uma nova revisão.':'Uma fonte exige revisão avançada antes do staging. Nenhum item foi publicado.'}finally{acting.value=false}}
async function runPreflight(){if(!closing.value||!review.value)return;acting.value=true;errorMessage.value='';try{preflight.value=(await FinancialClosingService.preflightWorkbookReview(closing.value.id,review.value.id,review.value.revision)).data;review.value=(await FinancialClosingService.workbookReview(closing.value.id,review.value.id)).data}catch(error:any){errorMessage.value=error?.response?.status===409?'A preparação mudou ou expirou. Atualize a revisão antes de publicar.':'Não foi possível concluir a conferência.'}finally{acting.value=false}}
async function publish(){if(!closing.value||!review.value||!review.value.preflightHmac)return;acting.value=true;errorMessage.value='';try{const storageKey=`closing-workbook-publication:${review.value.id}`;let key=sessionStorage.getItem(storageKey);if(!key){key=crypto.randomUUID();sessionStorage.setItem(storageKey,key)}publication.value=(await FinancialClosingService.publishWorkbookReview(closing.value.id,review.value.id,{expectedRevision:review.value.revision,preflightHmac:review.value.preflightHmac,idempotencyKey:key})).data;review.value=(await FinancialClosingService.workbookReview(closing.value.id,review.value.id)).data}catch(error:any){errorMessage.value=error?.response?.status===409?'O preflight ficou desatualizado. Reabra a conferência antes de tentar novamente.':'A publicação não foi concluída; nenhum item parcial ficou visível.'}finally{acting.value=false}}
function backToPanel(){router.push({name:'planning-financial-closings',query:{closingId:closing.value?.id}})}function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)}function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}onMounted(initialize)
</script>

<style scoped>
.import-wizard{min-height:100vh;background:var(--cb-surface-soft,#f6f7fb);padding:20px}.wizard-shell{max-width:820px;margin:0 auto}.wizard-header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;margin-bottom:14px}.wizard-header h1{font-size:1.45rem;margin:2px 0}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.72rem;color:var(--cb-text-muted,#667085);margin:0}.wizard-card{margin-top:18px;padding:28px;display:grid;gap:18px}.wizard-card h2{font-size:1.5rem;margin:0}.wizard-card>p{color:var(--cb-text-muted,#667085);margin:0}.wizard-state{display:grid;place-items:center}.source-list{list-style:none;padding:0;display:grid;gap:10px}.source-list li{display:flex;gap:12px;padding:14px;background:#f7f8fb;border-radius:10px}.source-list small{display:block;color:var(--cb-text-muted,#667085)}.notice{padding:14px;border-left:4px solid #b7791f;background:#fffaf0}.notice p{margin:4px 0}.summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.summary div{padding:14px;background:#f7f8fb;border-radius:10px}.summary dt{color:var(--cb-text-muted,#667085);font-size:.85rem}.summary dd{font-weight:700;margin:5px 0 0}.sticky-action{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0;color:var(--cb-text-muted,#667085)}@media(max-width:600px){.import-wizard{padding:12px 12px 88px}.wizard-header{grid-template-columns:1fr auto}.wizard-header>.v-btn{grid-column:1/-1;justify-self:start}.wizard-card{padding:18px 16px}.summary{grid-template-columns:1fr}.wizard-card>.v-btn{width:100%;min-height:48px}.sticky-action{position:fixed;left:0;right:0;bottom:0;background:white;border-top:1px solid #e7e9ef;padding:10px 12px;z-index:5}.sticky-action span{font-size:.78rem;max-width:60%}}
</style>
