<template>
  <div class="cb-page closing-panel">
    <div class="cb-container">
      <page-header title="Apuração de resultados" :summary-items="headerSummary">
        <template #actions><v-btn color="primary" prepend-icon="mdi-calendar-plus" @click="showCreate = !showCreate">Abrir ou criar competência</v-btn></template>
      </page-header>

      <alert-strip v-if="errorMessage" variant="info" :description="errorMessage" />
      <div v-if="loading" class="cb-empty-state" role="status"><v-progress-circular indeterminate /><p>Carregando competência…</p></div>
      <div v-else-if="!selectedClosing" class="cb-empty-state">
        <v-icon size="44">mdi-calendar-plus</v-icon><p class="cb-empty-state__title">Comece uma competência</p>
        <p>Crie o período antes de preparar os dados de origem.</p>
        <div class="create-row"><v-select v-model="month" :items="months" label="Mês" /><v-text-field v-model.number="year" label="Ano" type="number" /><v-btn color="primary" :loading="creating" @click="createClosing">Criar competência</v-btn></div>
      </div>
      <template v-else>
        <section class="competence cb-card" aria-label="Competência atual">
          <v-select v-model="selectedId" :items="closingOptions" item-title="title" item-value="value" label="Competência" hide-details />
          <div class="badges"><v-chip size="small" variant="tonal">Versão {{ selectedClosing.currentVersion.versionNumber }}</v-chip><v-chip size="small" :color="selectedClosing.workflowStatus === 'DRAFT' ? 'warning' : 'success'" variant="tonal">{{ selectedClosing.workflowStatus === 'DRAFT' ? 'Em preparação' : selectedClosing.workflowStatus }}</v-chip></div>
          <v-btn variant="text" @click="showCreate = !showCreate">Abrir outra competência</v-btn>
        </section>
        <section v-if="showCreate" class="cb-card create-competence" aria-labelledby="create-competence-title"><div><p class="eyebrow">Competência da apuração</p><h2 id="create-competence-title">Abrir ou criar uma competência</h2><p>Cada mês possui uma única apuração no escopo DEFAULT. Se ela já existir, abriremos sua versão atual sem duplicar dados.</p></div><div class="create-row"><v-select v-model="month" :items="months" label="Mês" /><v-text-field v-model.number="year" label="Ano" type="number" /><v-btn color="primary" :loading="creating" @click="createClosing">Abrir ou criar</v-btn></div></section>

        <main class="journey-grid" aria-label="Etapas do fechamento">
          <article class="journey-card cb-card" :class="{ active: sourceActive }">
            <div class="step-number">1</div><div><p class="eyebrow">Base editável</p><h2>{{ sourceTitle }}</h2><p>{{ sourceDescription }}</p><small>{{ publishedSourceCount }} de {{ expectedSourceCount }} fonte(s) esperada(s) materializada(s) para o cálculo</small><small v-if="publishedSourceCount>1">Cada lote pode ser conferido ou retirado até a publicação financeira.</small></div>
            <div class="card-actions"><v-btn v-if="canImport" color="primary" @click="openImport">{{ sourceAction }}</v-btn></div>
            <div v-if="lotsLoading" class="lots-state" role="status"><v-progress-circular indeterminate size="20" /> Carregando lotes da base…</div>
            <alert-strip v-else-if="lotsError" class="lots-state" variant="info" :description="lotsError" />
            <div v-else-if="lots.length" class="lots" aria-label="Lotes da base editável">
              <article v-for="lot in lots" :key="lot.publicationId" class="lot" :class="{ inactive: !lot.active }">
                <header class="lot-heading"><div><p class="lot-kicker">Lote de importação</p><strong>{{ lotLabel(lot) }}</strong><small>{{ lotStatus(lot) }} · {{ lot.sources.filter(source=>source.active).length }} de {{ lot.sources.length }} fonte(s) ativa(s)</small></div><v-chip size="small" :color="lot.active ? 'success' : undefined" variant="tonal">{{ lot.active ? 'Ativo' : 'Histórico' }}</v-chip></header>
                <div class="lot-impact" aria-label="Impacto atual do lote"><span>Itens ativos <strong>{{ lot.itemCount }}</strong></span><span>Adições <strong>{{ money(lot.additionTotal) }}</strong></span><span>Reversões <strong>{{ money(lot.reversalTotal) }}</strong></span><span>Impacto líquido <strong>{{ money(lot.netImpact) }}</strong></span></div>
                <section class="lot-sources" :aria-label="`Fontes do ${lotLabel(lot)}`">
                  <article v-for="source in lot.sources" :key="source.reviewSourceId" class="lot-source" :class="{ inactive: !source.active }">
                    <div class="source-heading"><div><strong>{{ source.sourceKey }}</strong><small>{{ source.active ? 'Incluída na base editável' : 'Retirada da base' }} · {{ source.itemCount }} item(ns)</small></div><v-chip size="x-small" :color="source.active ? 'success' : undefined" variant="tonal">{{ source.active ? 'Ativa' : 'Histórico' }}</v-chip></div>
                    <div class="source-impact"><span>Adições {{ money(source.additionTotal) }}</span><span>Reversões {{ money(source.reversalTotal) }}</span><strong>Impacto {{ money(source.netImpact) }}</strong></div>
                    <div class="source-lot-actions"><v-btn size="small" variant="text" @click="openLotSource(lot,source)">Ver itens</v-btn><v-btn v-if="source.active&&rulesAvailable" size="small" variant="text" @click="openRulesForLotSource(source)">Configurar regras</v-btn><v-btn v-if="source.mutable" size="small" variant="tonal" :loading="replacingSource===source.reviewSourceId" @click="replaceSource(lot,source)">Substituir esta fonte</v-btn><v-btn v-if="source.mutable" size="small" color="error" variant="text" :loading="removingSource===source.reviewSourceId" @click="removeSource(lot,source)">Retirar esta fonte</v-btn></div>
                  </article>
                </section>
                <footer class="lot-actions"><span>Ações sobre todas as fontes deste arquivo</span><v-btn size="small" variant="text" @click="openLot(lot)">Ver lote completo</v-btn><v-btn v-if="lot.mutable" size="small" variant="tonal" :loading="replacingLot===lot.reviewId" @click="replaceLot(lot)">Substituir arquivo inteiro</v-btn><v-btn v-if="lot.mutable" size="small" color="error" variant="text" :loading="removingLot===lot.reviewId" @click="removeLot(lot)">Retirar lote inteiro</v-btn></footer>
              </article>
              <p v-if="invalidationDescription" class="invalidation-note"><v-icon size="18">mdi-alert-circle-outline</v-icon>{{ invalidationDescription }}</p>
            </div>
            <div v-else class="lots-state cb-empty-state"><v-icon>mdi-database-off-outline</v-icon><p class="cb-empty-state__title">Nenhum lote ativo na base</p><p>Importe uma fonte para montar a base editável desta competência.</p></div>
            <div v-if="pendingReadinessSources.length" class="source-readiness" aria-label="Fontes esperadas fora da base"><p class="source-readiness-title">Fontes esperadas ainda fora da base</p><div v-for="source in pendingReadinessSources" :key="source.sourceId" class="source-row"><div><strong>{{ source.displayName }}</strong><small>{{ sourceLabel(source.sourceStatus || source.status) }} · {{ sourceDetail(source) }}</small></div><div class="source-actions"><v-btn v-if="(source.allowedActions||[]).includes('IMPORT_SOURCE')" size="small" variant="tonal" @click="openImport">Importar fonte</v-btn><v-btn v-if="(source.allowedActions||[]).includes('DECLARE_NO_ACTIVITY')" size="small" variant="text" @click="declareNoActivity(source)">Declarar sem movimento</v-btn><v-btn v-if="(source.allowedActions||[]).includes('REOPEN_SOURCE')" size="small" variant="tonal" @click="reopenSource(source)">Reabrir fonte</v-btn></div></div></div>
          </article>
          <article class="journey-card cb-card" :class="{ active: rulesAvailable }">
            <div class="step-number">2</div><div><p class="eyebrow">Regras do cálculo</p><h2>{{ rulesTitle }}</h2><p>{{ rulesDescription }}</p></div>
            <v-btn class="card-action" variant="tonal" :disabled="!rulesAvailable" @click="openRules">{{ rulesAction }}</v-btn>
          </article>
          <article class="journey-card cb-card" :class="{ active: resultAvailable }">
            <div class="step-number">3</div><div><p class="eyebrow">Resultado calculado e revisão</p><h2>{{ resultAvailable ? (financiallyPublished ? 'Resultado publicado financeiramente' : 'Resultado pronto para revisão') : 'Aguardando cálculo' }}</h2><p>{{ financiallyPublished ? 'A confirmação financeira atual está registrada e auditada.' : 'Calcule e revise os valores. A publicação financeira acontece somente após essa conferência.' }}</p></div>
            <v-btn class="card-action" variant="tonal" :disabled="!rulesAvailable" @click="openResult">{{ resultAvailable ? (financiallyPublished ? 'Ver publicação financeira' : 'Revisar resultado') : 'Calcular resultado' }}</v-btn>
          </article>
          <article class="journey-card cb-card" :class="{ active: decisionAvailable }">
            <div class="step-number">4</div><div><p class="eyebrow">Decisão</p><h2>{{ decisionTitle }}</h2><p>{{ decisionDescription }}</p></div>
            <v-btn class="card-action" variant="tonal" :disabled="!decisionAvailable" @click="openDecision">{{ decisionAction }}</v-btn>
          </article>
        </main>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '@/components/PageHeader.vue'
import AlertStrip from '@/components/AlertStrip.vue'
import FinancialClosingService, { type DeductionReadiness, type FinancialClosing, type ImportReadiness, type ImportReadinessSource, type MaterializedLot, type MaterializedLotSource, type PayoutDecision, type WorkbookReviewProgress } from '@/services/FinancialClosingService'

const route=useRoute(),router=useRouter();const closings=ref<FinancialClosing[]>([]),selectedId=ref(''),progress=ref<WorkbookReviewProgress|null>(null),lots=ref<MaterializedLot[]>([]),importReadiness=ref<ImportReadiness|null>(null),deductionReadiness=ref<DeductionReadiness|null>(null),payoutDecision=ref<PayoutDecision|null>(null),loading=ref(true),lotsLoading=ref(false),creating=ref(false),removingLot=ref(''),replacingLot=ref(''),removingSource=ref(''),replacingSource=ref(''),showCreate=ref(false),errorMessage=ref(''),lotsError=ref('');const month=ref(new Date().getMonth()+1),year=ref(new Date().getFullYear());
const months=Array.from({length:12},(_,index)=>({title:String(index+1).padStart(2,'0'),value:index+1}));
const selectedClosing=computed(()=>closings.value.find(item=>item.id===selectedId.value)||null);const closingOptions=computed(()=>closings.value.map(item=>({title:`${String(item.periodMonth).padStart(2,'0')}/${item.periodYear} · ${item.closingKey}`,value:item.id})));
const headerSummary=computed(()=>selectedClosing.value?[{label:'Competência',value:`${String(selectedClosing.value.periodMonth).padStart(2,'0')}/${selectedClosing.value.periodYear}`},{label:'Escopo',value:selectedClosing.value.closingKey}]:[]);
const expectedSourceCount=computed(()=>importReadiness.value?.sources.length||0);const sourcePublished=(source:ImportReadinessSource)=>(source.sourceStatus||source.status||'').endsWith('_PUBLISHED')||source.status==='IMPORTED';const publishedSourceCount=computed(()=>importReadiness.value?.sources.filter(sourcePublished).length||0);const inputsReady=computed(()=>importReadiness.value?.readyToCalculate===true);const hasPublishedInputs=computed(()=>lots.value.some(lot=>lot.active));const hasActiveReview=computed(()=>Boolean(progress.value&&!['PUBLISHED','ABANDONED','EXPIRED'].includes(progress.value.status)));const canImport=computed(()=>selectedClosing.value?.workflowStatus==='DRAFT'&&selectedClosing.value?.currentVersion.versionStatus==='EDITABLE');const sourceActive=computed(()=>canImport.value),rulesAvailable=computed(()=>inputsReady.value),resultAvailable=computed(()=>Boolean(selectedClosing.value?.currentVersion.calculationCurrent)),financiallyPublished=computed(()=>Boolean(selectedClosing.value?.currentVersion.financialPublicationCurrent)),decisionAvailable=computed(()=>financiallyPublished.value||Boolean(payoutDecision.value));
const activeSourceIds=computed(()=>new Set(lots.value.flatMap(lot=>lot.sources.filter(source=>source.active).map(source=>source.sourceId))));const pendingReadinessSources=computed(()=>(importReadiness.value?.sources||[]).filter(source=>!activeSourceIds.value.has(source.sourceId)));
const invalidationDescription=computed(()=>{const version=selectedClosing.value?.currentVersion;if(!version||version.calculationCurrent)return '';if(version.calculatedRevision==null)return '';return `A base foi alterada após o cálculo da revisão ${version.calculatedRevision}. Recalcule e revise o resultado antes de uma nova publicação financeira.`});
const sourceTitle=computed(()=>hasActiveReview.value?'Importação em andamento':inputsReady.value?'Base de cálculo pronta para revisão':hasPublishedInputs.value?'Fontes restantes pendentes':'Montar base de cálculo');
const sourceDescription=computed(()=>hasActiveReview.value?'Retome a revisão ativa antes de iniciar outro lote.':inputsReady.value&&canImport.value?'As fontes atuais formam uma base editável. Você pode acrescentar, substituir ou retirar lotes antes de confirmar o resultado financeiro.':inputsReady.value?'Todas as fontes configuradas estão materializadas para o cálculo.':hasPublishedInputs.value?'Há fontes na base e fontes ainda pendentes. Você pode adicionar um lote não sobreposto antes do cálculo.':progress.value?.status==='PUBLISHED'&&!progress.value?.contributingPublication?'O lote anterior não trouxe itens e permanece somente no histórico. Prepare as fontes pendentes.':'Selecione o workbook para iniciar uma revisão rastreável.');
const sourceAction=computed(()=>hasActiveReview.value?'Continuar revisão do lote':hasPublishedInputs.value?'Preparar novo lote':'Importar workbook');
const rulesTitle=computed(()=>!rulesAvailable.value?'Aguardando dados':deductionReadiness.value?.readyToCalculate?'Regras revisadas':'Revisão necessária');
const rulesDescription=computed(()=>!rulesAvailable.value?'Adicione os dados de origem à base editável para revisar as incidências.':deductionReadiness.value?.readyToCalculate?'Todas as fontes possuem uma declaração atual.':`${deductionReadiness.value?.blockingSourceKeys.length||0} fonte(s) aguardam revisão.`);
const rulesAction=computed(()=>deductionReadiness.value?.readyToCalculate?'Ver regras':'Revisar regras');
const decisionTitle=computed(()=>payoutDecision.value?.status==='APPROVED'?'Decisão aprovada':payoutDecision.value?.status==='REVIEW'?'Aguardando autorização final':payoutDecision.value?.status==='DRAFT'?'Proposta em preparação':decisionAvailable.value?'Pronta para decisão':'Aguardando resultado atual');
const decisionDescription=computed(()=>payoutDecision.value?.status==='APPROVED'?`${payoutDecision.value.issuedObligationCount} obrigação(ões) emitida(s), sem executar transferência bancária.`:payoutDecision.value?.status==='REVIEW'?'A proposta está bloqueada para edição e aguarda um aprovador elegível.':payoutDecision.value?.status==='DRAFT'?'Revise os Valores a Receber antes de enviar para autorização.':'A aprovação usa somente o Valor a Receber e preserva TM, TI e reservas.');
const decisionAction=computed(()=>payoutDecision.value?.status==='APPROVED'?'Ver decisão':payoutDecision.value?.status==='REVIEW'?'Revisar autorização':payoutDecision.value?.status==='DRAFT'?'Continuar proposta':'Preparar decisão');
async function load(){loading.value=true;errorMessage.value='';try{closings.value=(await FinancialClosingService.list()).data;const requested=String(route.query.closingId||route.params.closingId||'');selectedId.value=closings.value.some(item=>item.id===requested)?requested:(closings.value[0]?.id||'');await loadProgress()}catch{errorMessage.value='Não foi possível carregar o painel da competência.'}finally{loading.value=false}}
async function loadProgress(){const closing=selectedClosing.value;if(!closing){progress.value=null;lots.value=[];importReadiness.value=null;deductionReadiness.value=null;payoutDecision.value=null;return}lotsLoading.value=true;lotsError.value='';try{lots.value=(await FinancialClosingService.materializedLots(closing)).data}catch{lots.value=[];lotsError.value='Não foi possível carregar os lotes da base editável.'}finally{lotsLoading.value=false}try{const response=await FinancialClosingService.latestWorkbookReview(closing);progress.value=response.status===204?null:(response.data||null)}catch{progress.value=null}try{importReadiness.value=(await FinancialClosingService.importReadiness(closing)).data}catch{importReadiness.value=null}if(inputsReady.value){try{deductionReadiness.value=(await FinancialClosingService.deductionReadiness(closing)).data}catch{deductionReadiness.value=null}}else deductionReadiness.value=null;try{const decisions=(await FinancialClosingService.payoutDecisions(closing)).data;payoutDecision.value=decisions.find(item=>item.status==='REVIEW')||decisions.find(item=>item.status==='DRAFT')||decisions.find(item=>item.status==='APPROVED')||null}catch{payoutDecision.value=null}}
async function createClosing(){creating.value=true;try{const created=(await FinancialClosingService.createOrGet(month.value,year.value,'DEFAULT','BRL')).data;await load();selectedId.value=created.id;showCreate.value=false}catch{errorMessage.value='Não foi possível criar a competência.'}finally{creating.value=false}}
function sourceLabel(status?:string){return ({REQUIRED_PENDING:'Obrigatória pendente',REQUIRED_PUBLISHED:'Na base de cálculo',REQUIRED_NO_ACTIVITY:'Sem movimento declarado',OPTIONAL_NOT_INCLUDED:'Opcional não incluída',OPTIONAL_IN_PROGRESS:'Importação opcional em andamento',OPTIONAL_PUBLISHED:'Na base de cálculo'} as Record<string,string>)[status||'']||'Pendente'}
function sourceDetail(source:ImportReadinessSource){const status=source.sourceStatus||source.status||'';return ({REQUIRED_PENDING:'Importe esta fonte ou declare que não houve movimento.',REQUIRED_PUBLISHED:'Os itens materializados integram a base editável. Escolha as regras desta fonte antes do cálculo.',REQUIRED_NO_ACTIVITY:'Reabra a fonte antes de importar novos itens.',OPTIONAL_NOT_INCLUDED:'A fonte opcional não participa desta competência.',OPTIONAL_IN_PROGRESS:'Conclua ou abandone a importação opcional em andamento.',OPTIONAL_PUBLISHED:'Os itens materializados integram a base editável. Escolha as regras desta fonte antes do cálculo.',IMPORTED:'Os itens materializados integram a base editável. Escolha as regras desta fonte antes do cálculo.'} as Record<string,string>)[status]||source.detail}
async function declareNoActivity(source:ImportReadinessSource){const closing=selectedClosing.value;const justification=window.prompt('Justifique a ausência de movimento desta fonte.');if(!closing||!justification?.trim()||source.expectedSourceRevision==null)return;try{await FinancialClosingService.declareSourceNoActivity(closing,source.sourceId,source.expectedSourceRevision,justification.trim());await loadProgress()}catch{errorMessage.value='Não foi possível declarar a fonte sem movimento. Atualize e tente novamente.'}}
async function reopenSource(source:ImportReadinessSource){const closing=selectedClosing.value;const justification=window.prompt('Justifique a reabertura desta fonte.');if(!closing||!justification?.trim()||source.expectedSourceRevision==null)return;try{await FinancialClosingService.reopenSource(closing,source.sourceId,source.expectedSourceRevision,justification.trim());await loadProgress()}catch{errorMessage.value='Não foi possível reabrir a fonte. Atualize e tente novamente.'}}
function openImport(){const closing=selectedClosing.value;if(!closing||!canImport.value)return;router.push({name:'closing-import-wizard',params:{closingId:closing.id,reviewId:hasActiveReview.value?progress.value?.id||'new':'new'}})}
function openPublicationHistory(){const closing=selectedClosing.value;if(closing&&progress.value)router.push({name:'closing-publication-history',params:{closingId:closing.id,reviewId:progress.value.id}})}
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:selectedClosing.value?.currency||'BRL'}).format(Number(value||0))}
function lotStatus(lot:MaterializedLot){return ({MATERIALIZED:'Na base editável',FINANCIALLY_PUBLISHED:'Incluído em publicação financeira',CANCELLED:'Retirado ou substituído',PUBLISHED:'Materializado (legado)'} as Record<string,string>)[lot.status]||lot.status}
function lotLabel(lot:MaterializedLot){return `Lote de ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(lot.materializedAt))}`}
function openLot(lot:MaterializedLot){const closing=selectedClosing.value;if(closing)router.push({name:'closing-publication-history',params:{closingId:closing.id,reviewId:lot.reviewId}})}
function openLotSource(lot:MaterializedLot,source:MaterializedLotSource){const closing=selectedClosing.value;if(closing)router.push({name:'closing-publication-history',params:{closingId:closing.id,reviewId:lot.reviewId},query:{sourceId:source.sourceId}})}
async function removeLot(lot:MaterializedLot){const closing=selectedClosing.value;if(!closing||!lot.mutable||!window.confirm('Retirar este lote da base editável? O cálculo e qualquer revisão anterior deixarão de ser atuais.'))return;removingLot.value=lot.reviewId;errorMessage.value='';try{await FinancialClosingService.cancelWorkbookMaterialization(closing.id,lot.reviewId);closing.currentVersion.calculationCurrent=false;closing.currentVersion.financialPublicationCurrent=false;await loadProgress()}catch{errorMessage.value='Não foi possível retirar o lote. Atualize a competência e tente novamente.'}finally{removingLot.value=''}}
async function replaceLot(lot:MaterializedLot){const closing=selectedClosing.value;if(!closing||!lot.mutable||!window.confirm('Substituir este lote? O lote atual será preservado no histórico e retirado da base antes do envio do novo arquivo.'))return;replacingLot.value=lot.reviewId;errorMessage.value='';try{await FinancialClosingService.cancelWorkbookMaterialization(closing.id,lot.reviewId);closing.currentVersion.calculationCurrent=false;closing.currentVersion.financialPublicationCurrent=false;await router.push({name:'closing-import-wizard',params:{closingId:closing.id,reviewId:'new'},query:{replaces:lot.reviewId}})}catch{errorMessage.value='Não foi possível iniciar a substituição do lote. Atualize a competência e tente novamente.'}finally{replacingLot.value=''}}
async function removeSource(lot:MaterializedLot,source:MaterializedLotSource){const closing=selectedClosing.value;if(!closing||!source.mutable||!window.confirm(`Retirar somente ${source.sourceKey} da base editável? As outras fontes deste lote serão preservadas.`))return;removingSource.value=source.reviewSourceId;errorMessage.value='';try{await FinancialClosingService.cancelWorkbookSourceMaterialization(closing.id,lot.reviewId,source.reviewSourceId);closing.currentVersion.calculationCurrent=false;closing.currentVersion.financialPublicationCurrent=false;await loadProgress()}catch{errorMessage.value='Não foi possível retirar esta fonte. Atualize a competência e tente novamente.'}finally{removingSource.value=''}}
async function replaceSource(lot:MaterializedLot,source:MaterializedLotSource){const closing=selectedClosing.value;if(!closing||!source.mutable||!window.confirm(`Substituir somente ${source.sourceKey}? As outras fontes deste lote permanecerão na base.`))return;replacingSource.value=source.reviewSourceId;errorMessage.value='';try{await FinancialClosingService.cancelWorkbookSourceMaterialization(closing.id,lot.reviewId,source.reviewSourceId);closing.currentVersion.calculationCurrent=false;closing.currentVersion.financialPublicationCurrent=false;await router.push({name:'closing-import-wizard',params:{closingId:closing.id,reviewId:'new'},query:{replacesSource:source.sourceId,sourceKey:source.sourceKey}})}catch{errorMessage.value='Não foi possível iniciar a substituição desta fonte. Atualize a competência e tente novamente.'}finally{replacingSource.value=''}}
function openRulesForLotSource(source:MaterializedLotSource){const readiness=importReadiness.value?.sources.find(item=>item.sourceId===source.sourceId);if(readiness)openRulesForSource(readiness)}
function openRulesForSource(source:ImportReadinessSource){const closing=selectedClosing.value;if(closing)router.push({name:'closing-rules',params:{closingId:closing.id},query:{sourceId:source.sourceId}})}
function openRules(){const closing=selectedClosing.value;if(closing)router.push({name:'closing-rules',params:{closingId:closing.id}})}
function openResult(){const closing=selectedClosing.value;if(closing)router.push({name:'closing-result',params:{closingId:closing.id}})}
function openDecision(){const closing=selectedClosing.value;if(closing)router.push({name:'closing-decision',params:{closingId:closing.id}})}
watch(selectedId,loadProgress);onMounted(load)
</script>

<style scoped>
.lots,.lots-state{grid-column:1/-1}.lots{display:grid;gap:14px}.lot{display:grid;gap:16px;padding:18px;border:1px solid var(--cb-border,#d9dde7);border-radius:14px;background:var(--cb-surface,#fff);box-shadow:0 5px 18px rgba(16,24,40,.05)}.lot.inactive{opacity:.72}.lot-heading,.source-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.lot-heading small,.source-heading small{display:block;margin-top:4px;color:var(--cb-text-muted,#667085)}.lot-kicker{margin:0 0 4px!important;text-transform:uppercase;letter-spacing:.08em;font-size:.68rem;color:var(--cb-text-muted,#667085)}.lot-impact{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;padding:12px;border-radius:10px;background:var(--cb-surface-soft,#f6f7fb);font-size:.82rem;color:var(--cb-text-muted,#667085)}.lot-impact span{display:grid;gap:3px}.lot-impact strong{color:var(--cb-text,#162033)}.lot-sources{display:grid;gap:10px}.lot-source{display:grid;gap:10px;padding:14px;border:1px solid var(--cb-border,#d9dde7);border-left:4px solid var(--cb-primary,#3451b2);border-radius:10px;background:#fff}.lot-source.inactive{border-left-color:var(--cb-border,#d9dde7);background:var(--cb-surface-soft,#f6f7fb)}.source-impact,.source-lot-actions,.lot-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.source-impact{justify-content:space-between;font-size:.78rem;color:var(--cb-text-muted,#667085)}.source-impact strong{color:var(--cb-text,#162033)}.lot-actions{padding-top:12px;border-top:1px solid var(--cb-border,#d9dde7)}.lot-actions>span{margin-right:auto;font-size:.75rem;color:var(--cb-text-muted,#667085)}.lots-state{padding:16px}.invalidation-note{display:flex;align-items:center;gap:8px;margin:2px 0 0;color:var(--cb-warning,#9a6700)}
.closing-panel{min-height:100vh;background:var(--cb-surface-soft,#f6f7fb)}.competence{display:flex;align-items:center;gap:18px;padding:16px;margin-bottom:18px}.competence :deep(.v-input){max-width:440px}.badges{display:flex;gap:8px;flex-wrap:wrap}.create-competence{padding:18px;margin:-4px 0 18px}.create-competence h2{font-size:1.15rem;margin:3px 0 8px}.create-competence p{color:var(--cb-text-muted,#667085);margin:0}.journey-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.journey-card{display:grid;grid-template-columns:auto 1fr;gap:14px;padding:20px;opacity:.72}.journey-card.active{opacity:1;border:1px solid color-mix(in srgb,var(--cb-primary,#3451b2) 35%,transparent)}.journey-card h2{font-size:1.2rem;margin:3px 0 8px}.journey-card p{color:var(--cb-text-muted,#667085);margin:0}.journey-card small{display:block;margin-top:10px}.step-number{display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:var(--cb-primary,#3451b2);color:white;font-weight:700}.card-actions{grid-column:2;display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:6px}.source-readiness{grid-column:1/-1;display:grid;gap:8px}.source-readiness-title{margin:0;font-size:.78rem;font-weight:700;color:var(--cb-text-muted,#667085);text-transform:uppercase;letter-spacing:.06em}.source-row{display:flex;justify-content:space-between;gap:10px;padding:10px;border-radius:8px;background:var(--cb-surface-soft,#f6f7fb)}.source-row small{margin-top:2px}.source-actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.72rem}.create-row{display:grid;grid-template-columns:1fr 1fr auto;align-items:start;gap:12px;max-width:680px;width:100%;margin-top:14px}@media(max-width:700px){.competence{align-items:stretch;flex-direction:column}.competence :deep(.v-input){max-width:none}.journey-grid{grid-template-columns:1fr}.journey-card{grid-template-columns:auto 1fr;padding:16px}.card-actions{grid-column:1/-1;display:grid}.card-actions :deep(.v-btn){width:100%;min-height:48px}.source-row{flex-direction:column}.source-actions{display:grid}.source-actions :deep(.v-btn){width:100%;min-height:44px}.create-row{grid-template-columns:1fr}.lot-impact{grid-template-columns:repeat(2,minmax(0,1fr))}.source-impact{align-items:flex-start;flex-direction:column}.source-lot-actions,.lot-actions{display:grid}.source-lot-actions :deep(.v-btn),.lot-actions :deep(.v-btn){width:100%;min-height:42px}.lot-actions>span{margin:0}}
</style>
