<template>
  <div class="cb-page result-page"><div class="cb-container narrow">
    <v-btn variant="text" prepend-icon="mdi-arrow-left" @click="back">Voltar para a competência</v-btn>
    <page-header title="Resultado da apuração" :summary-items="headerSummary" />
    <alert-strip v-if="errorMessage" variant="info" :description="errorMessage" />
    <div v-if="loading" class="cb-empty-state" role="status"><v-progress-circular indeterminate/><p>Carregando resultado…</p></div>
    <template v-else-if="closing">
      <section v-if="!readiness?.readyToCalculate" class="cb-card blocked"><v-icon size="36" color="warning">mdi-alert-circle-outline</v-icon><div><h2>As regras ainda precisam de revisão</h2><p>{{ readiness?.blockingSourceKeys.length || 0 }} fonte(s) aguardam uma declaração atual.</p><v-btn color="primary" @click="openRules">Revisar regras</v-btn></div></section>
      <template v-else>
        <section class="cb-card result-state"><div><p class="eyebrow">Base canônica V29</p><h2>{{ summary ? 'Cálculo atual' : 'Prévia pronta para calcular' }}</h2><p v-if="summary">Execução congelada para a revisão {{ summary.inputRevision }}.</p><p v-else>A prévia usa o mesmo motor de PB → deduções → PL, mas ainda não cria uma execução.</p></div><v-chip :color="summary?'success':'warning'" variant="tonal">{{ summary?'Atual':'Não calculado' }}</v-chip></section>

        <section class="calculation-flow" aria-label="Etapas do cálculo"><article class="cb-card"><span>1. Receita da fonte</span><strong>Valor bruto − reversões − deduções da fonte</strong><small>As deduções configuráveis incidem somente depois das reversões.</small></article><article class="cb-card primary"><span>2. Produtividade Líquida (PL)</span><strong>{{ money(result?.netProductivityAmount) }}</strong><small>Resultado da etapa por fonte; não contém TM ou TI.</small></article><article class="cb-card"><span>3. Destinação da PL</span><strong>TM + TI + reserva por desempenho + Valor a Receber</strong><small>TM e TI são reservas automáticas; a pontuação define diretamente o Valor a Receber.</small></article></section>

        <div class="metrics" aria-label="Resumo da produtividade"><article class="cb-card"><span>Valor bruto das fontes</span><strong>{{ money(result?.grossProductivityAmount) }}</strong></article><article class="cb-card"><span>Deduções da fonte</span><strong>{{ money(result?.deductionAmount) }}</strong></article><article class="cb-card primary"><span>Produtividade Líquida</span><strong>{{ money(result?.netProductivityAmount) }}</strong></article><article v-if="summary" class="cb-card"><span>Valor a Receber</span><strong>{{ money(valueReceivable) }}</strong></article></div>

        <section class="section" aria-labelledby="sources-result-title"><div class="section-heading"><div><p class="eyebrow">Por fonte</p><h2 id="sources-result-title">Da Bruta à PL</h2><p>Valor bruto − reversões − deduções da fonte. TM e TI não são deduções desta etapa.</p></div></div><div class="source-grid"><article v-for="source in sourceResults" :key="source.sourceId" class="cb-card source-result"><strong>{{ source.displayName }}</strong><dl><div><dt>Valor bruto</dt><dd>{{ money(source.grossAmount) }}</dd></div><div><dt>Reversões</dt><dd>{{ money(source.reversalAmount) }}</dd></div><div><dt>Deduções da fonte</dt><dd>{{ money(source.deductionAmount) }}</dd></div><div><dt>PL resultante</dt><dd>{{ money(source.netProductivityAmount) }}</dd></div></dl></article></div></section>

        <section class="section" aria-labelledby="memory-title"><div class="section-heading"><div><p class="eyebrow">Memória auditável</p><h2 id="memory-title">Regras aplicadas</h2><p>O resumo é sempre agregado. Itens individuais exigem acesso sensível autorizado.</p></div></div><alert-strip v-if="protectedDetailMessage" variant="info" :description="protectedDetailMessage" /><div v-if="applications.length" class="application-list"><details v-for="application in applications" :key="`${application.ruleKey}-${application.ruleRevision}`" class="cb-card"><summary><span><strong>{{ application.ruleName }}</strong><small>{{ application.percentage }}% · revisão {{ application.ruleRevision }}</small></span><strong>{{ money(application.deductionAmount) }}</strong></summary><p>Base {{ application.baseReference==='CURRENT_BALANCE'?'saldo corrente':'Produtividade Bruta inicial' }}: {{ money(application.baseAmount) }}</p><p>Saldo {{ money(application.balanceBefore) }} → {{ money(application.balanceAfter) }}</p></details></div></section>

        <section v-if="missingScores.length" class="section cb-card score-setup" aria-labelledby="score-setup-title"><div class="section-heading"><div><p class="eyebrow">Etapa opcional</p><h2 id="score-setup-title">Registrar pontuações mensais</h2><p>{{ missingScores.length }} participante(s) têm Produtividade Líquida sem pontuação. A apuração pode seguir: somente participantes pontuados terão Valor a Receber nesta decisão.</p></div></div><article v-for="payout in missingScores" :key="payout.participantId" class="score-row"><div><strong>{{ participantName(payout.participantId) }}</strong><small>PL {{ money(payout.productivityAmount) }} · informe de 0% a 85% quando esta avaliação estiver disponível</small></div><v-text-field v-model.number="scoreValues[payout.participantId]" type="number" min="0" max="85" step="0.000001" label="Pontuação mensal" hide-details /><v-text-field v-model="scoreJustifications[payout.participantId]" label="Justificativa" hide-details /><v-btn color="primary" :disabled="!canSaveScore(payout.participantId)" :loading="savingScoreId===payout.participantId" @click="saveScore(payout.participantId)">Salvar pontuação</v-btn></article></section>

        <section v-if="summary?.participantPayouts?.length" class="section" aria-labelledby="payout-title"><div class="section-heading"><div><p class="eyebrow">Fatos calculados · somente leitura</p><h2 id="payout-title">Destinação da PL por participante</h2><p>TM e TI são reservas canônicas automáticas sobre a PL. Elas não reduzem a base usada para calcular o Valor a Receber.</p></div></div><div class="participant-grid"><article v-for="payout in summary.participantPayouts" :key="payout.participantId" class="cb-card"><strong>{{ participantName(payout.participantId) }}</strong><p>PL resultante {{ money(payout.productivityAmount) }}</p><dl><div><dt>Reserva TM · automática (10%)</dt><dd>{{ money(payout.tmReserveAmount) }}</dd></div><div><dt>Reserva TI · automática (5%)</dt><dd>{{ money(payout.tiReserveAmount) }}</dd></div><div><dt>Reserva adicional por desempenho</dt><dd>{{ money(payout.undistributedAmount) }}</dd></div><div><dt>Valor a Receber · derivado da pontuação</dt><dd>{{ money(payout.valueReceivableAmount) }}</dd></div><div><dt>Total explicado</dt><dd>{{ money(payout.totalExplainedAmount) }}</dd></div></dl></article></div></section>

        <div class="sticky-action"><p>{{ summary ? (missingScores.length ? 'Participantes sem pontuação ficarão fora desta proposta de pagamento.' : 'O resultado atual pode seguir para a decisão.') : 'Calcular congela a memória desta revisão.' }}</p><v-btn v-if="!summary" color="primary" size="large" :loading="calculating" @click="calculate">Calcular resultado</v-btn><v-btn v-else color="primary" size="large" @click="openDecision">Continuar para decisão</v-btn></div>
      </template>
    </template>
  </div></div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '@/components/PageHeader.vue'
import AlertStrip from '@/components/AlertStrip.vue'
import FinancialClosingService, { type CalculationMemory, type ClosingParticipant, type ClosingSummary, type DeductionPreview, type DeductionReadiness, type FinancialClosing } from '@/services/FinancialClosingService'

const route=useRoute(),router=useRouter();const closing=ref<FinancialClosing|null>(null),readiness=ref<DeductionReadiness|null>(null),preview=ref<DeductionPreview|null>(null),summary=ref<ClosingSummary|null>(null),memory=ref<CalculationMemory|null>(null),participants=ref<ClosingParticipant[]>([]),loading=ref(true),calculating=ref(false),savingScoreId=ref(''),errorMessage=ref(''),protectedDetailMessage=ref(''),scoreValues=reactive<Record<string,number|null>>({}),scoreJustifications=reactive<Record<string,string>>({});
const headerSummary=computed(()=>closing.value?[{label:'Competência',value:`${String(closing.value.periodMonth).padStart(2,'0')}/${closing.value.periodYear}`},{label:'Status',value:summary.value?'Cálculo atual':'Prévia'}]:[]);const result=computed(()=>summary.value||preview.value);const valueReceivable=computed(()=>summary.value?.participantPayouts?.reduce((total,item)=>total+Number(item.valueReceivableAmount||0),0)||0);const applications=computed(()=>memory.value?.deductionApplications||preview.value?.applications||[]);const sourceResults=computed(()=>{const calculated=summary.value?.sourceProductivity||[];if(calculated.length)return calculated.map(source=>({sourceId:source.sourceId,displayName:source.displayName,grossAmount:source.grossAmount,reversalAmount:source.reversalAmount,deductionAmount:source.retentionAmount,netProductivityAmount:source.netProductivityAmount}));return (preview.value?.sources||[]).map(source=>({sourceId:source.sourceId,displayName:source.displayName,grossAmount:source.grossProductivityAmount,reversalAmount:0,deductionAmount:source.deductionAmount,netProductivityAmount:source.netProductivityAmount}))});const missingScores=computed(()=>((summary.value?.participantPayouts||[]).filter(payout=>Number(payout.productivityAmount)>0&&payout.score==null)));const money=(value?:number|null)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:closing.value?.currency||'BRL'}).format(Number(value||0));const participantName=(id:string)=>participants.value.find(item=>item.id===id)?.displayName||'Participante';const canSaveScore=(participantId:string)=>{const score=scoreValues[participantId];return score!==null&&score!==undefined&&score>=0&&score<=85&&Boolean(scoreJustifications[participantId]?.trim())};
async function load(){loading.value=true;errorMessage.value='';try{const list=(await FinancialClosingService.list()).data;closing.value=list.find(item=>item.id===String(route.params.closingId))||null;if(!closing.value)throw new Error('missing');await loadResult()}catch{errorMessage.value='Não foi possível carregar o resultado desta competência.'}finally{loading.value=false}}
async function loadResult(){if(!closing.value)return;const [readinessResponse,participantsResponse]=await Promise.all([FinancialClosingService.deductionReadiness(closing.value),FinancialClosingService.participants(closing.value)]);readiness.value=readinessResponse.data;participants.value=participantsResponse.data;summary.value=null;memory.value=null;preview.value=null;protectedDetailMessage.value='';if(!readiness.value.readyToCalculate)return;if(closing.value.currentVersion.calculationCurrent){summary.value=(await FinancialClosingService.summary(closing.value)).data;try{memory.value=(await FinancialClosingService.memory(closing.value)).data}catch{protectedDetailMessage.value='O resumo agregado continua disponível. A memória detalhada exige acesso sensível autorizado para este fechamento.'}}else preview.value=(await FinancialClosingService.previewProductivityDeductions(closing.value)).data}
async function calculate(){if(!closing.value||!readiness.value?.readyToCalculate)return;calculating.value=true;try{summary.value=(await FinancialClosingService.calculate(closing.value)).data;try{memory.value=(await FinancialClosingService.memory(closing.value)).data}catch{protectedDetailMessage.value='O cálculo foi concluído. A memória detalhada exige acesso sensível autorizado para este fechamento.'}closing.value={...closing.value,currentVersion:{...closing.value.currentVersion,calculationCurrent:true,calculatedRevision:summary.value.inputRevision}}}catch{errorMessage.value='O cálculo não pôde ser concluído. Atualize as regras e tente novamente.'}finally{calculating.value=false}}
async function saveScore(participantId:string){if(!closing.value||!canSaveScore(participantId)||scoreValues[participantId]===null)return;savingScoreId.value=participantId;errorMessage.value='';try{await FinancialClosingService.upsertParticipantScore(closing.value,{participantId,score:Number(scoreValues[participantId]),justification:scoreJustifications[participantId].trim()});scoreValues[participantId]=null;scoreJustifications[participantId]='';const list=(await FinancialClosingService.list()).data;closing.value=list.find(item=>item.id===String(route.params.closingId))||closing.value;await loadResult()}catch{errorMessage.value='A pontuação deve estar entre 0% e 85% e exige justificativa.'}finally{savingScoreId.value=''}}
function back(){router.push({name:'planning-financial-closings',query:{closingId:closing.value?.id}})}function openRules(){if(closing.value)router.push({name:'closing-rules',params:{closingId:closing.value.id}})}function openDecision(){if(closing.value)router.push({name:'closing-decision',params:{closingId:closing.value.id}})}onMounted(load)
</script>

<style scoped>
.result-page{min-height:100vh;background:var(--cb-surface-soft,#f6f7fb);padding-bottom:110px}.narrow{max-width:1080px}.blocked,.result-state{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding:20px}.blocked{justify-content:flex-start}.blocked h2,.result-state h2{margin:3px 0}.blocked p,.result-state p,.score-setup p,.score-row small,.section-heading p,.calculation-flow small{color:var(--cb-text-muted,#667085)}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.72rem}.calculation-flow{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0}.calculation-flow article{display:grid;gap:7px;padding:16px}.calculation-flow strong{font-size:1rem}.calculation-flow .primary{border:1px solid var(--cb-primary,#3451b2)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.metrics article{display:grid;gap:6px;padding:16px}.metrics strong{font-size:1.35rem}.metrics .primary{border:1px solid var(--cb-primary,#3451b2)}.section{margin-top:24px}.section-heading{margin-bottom:12px}.source-grid,.participant-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.source-result,.participant-grid article,.score-setup{padding:16px}.source-result dl,.participant-grid dl{display:grid;gap:7px;margin:14px 0 0}.source-result dl div,.participant-grid dl div{display:flex;justify-content:space-between;gap:12px}.source-result dt,.participant-grid dt{color:var(--cb-text-muted,#667085)}.source-result dd,.participant-grid dd{margin:0;font-weight:600}.score-row{display:grid;grid-template-columns:1.2fr .65fr 1fr auto;align-items:center;gap:12px;padding:12px 0;border-top:1px solid #e7e9ef}.score-row>div{display:grid;gap:4px}.application-list{display:grid;gap:10px}.application-list details{padding:14px}.application-list summary{display:flex;justify-content:space-between;align-items:center;gap:12px;cursor:pointer;min-height:44px}.application-list summary span{display:grid}.application-list small{color:var(--cb-text-muted,#667085)}.sticky-action{position:fixed;z-index:5;left:0;right:0;bottom:0;display:flex;justify-content:center;align-items:center;gap:18px;padding:12px max(20px,env(safe-area-inset-right)) calc(12px + env(safe-area-inset-bottom));background:color-mix(in srgb,var(--cb-surface,#fff) 94%,transparent);border-top:1px solid #ddd}.sticky-action p{margin:0;color:var(--cb-text-muted,#667085)}@media(max-width:800px){.calculation-flow,.metrics{grid-template-columns:repeat(2,1fr)}.score-row{grid-template-columns:1fr 1fr}}@media(max-width:600px){.calculation-flow,.source-grid,.participant-grid,.score-row{grid-template-columns:1fr}.blocked,.result-state{align-items:flex-start;flex-direction:column}.sticky-action{align-items:stretch;flex-direction:column;gap:6px}.sticky-action .v-btn,.score-row .v-btn{width:100%;min-height:48px}.result-page{padding-bottom:145px}.application-list summary{align-items:flex-start}}
</style>
