<template>
  <div class="cb-page import-wizard"><div class="wizard-shell">
    <header class="wizard-header"><v-btn variant="text" prepend-icon="mdi-arrow-left" @click="backToPanel">Voltar</v-btn><div><p class="eyebrow">Importação da competência</p><h1>{{ competenceLabel }}</h1></div><v-chip size="small" variant="tonal">Etapa {{ step }} de 4</v-chip></header>
    <v-progress-linear :model-value="step*25" color="primary" height="6" rounded aria-label="Progresso da importação" />
    <alert-strip v-if="errorMessage" variant="info" :description="errorMessage" />
    <main class="wizard-card cb-card">
      <div v-if="loading" class="wizard-state" role="status"><v-progress-circular indeterminate /><p>Carregando revisão…</p></div>
      <template v-else-if="published">
        <v-icon color="success" size="52">mdi-check-circle-outline</v-icon><h2>Lote publicado</h2><p>As fontes foram publicadas juntas e agora estão disponíveis para o próximo gate do fechamento.</p><dl class="summary"><div><dt>Fontes</dt><dd>{{ publication?.sourceCount ?? review?.selectedSourceCount }}</dd></div><div><dt>Itens</dt><dd>{{ publication?.itemCount ?? totalCandidates }}</dd></div></dl><v-btn color="primary" @click="backToPanel">Voltar ao painel</v-btn>
      </template>
      <template v-else-if="expiredReview">
        <v-icon color="warning" size="48">mdi-clock-alert-outline</v-icon><p class="eyebrow">Revisão expirada</p><h2>Inicie uma nova revisão</h2><p>O prazo de 30 dias terminou. Nenhum staging ou decisão expirada pode ser publicado, e nenhum fato financeiro foi criado.</p><v-btn color="primary" @click="startNewReview">Começar nova revisão</v-btn>
      </template>
      <template v-else-if="needsResumeIntent">
        <p class="eyebrow">Retomar com segurança</p><h2>A revisão foi preservada</h2><p>O arquivo não fica armazenado. Confirme novamente a intenção de acessar dados protegidos. Se o staging expirou, o mesmo workbook será solicitado e seu fingerprint será conferido.</p><div v-if="progress?.stagingExpired" class="notice"><strong>O staging expirou</strong><p>As decisões sanitizadas continuam disponíveis. Reenvie o mesmo arquivo para reconstruir somente os candidatos compatíveis.</p></div><v-checkbox v-model="sensitiveConfirmed" label="Entendo que acessarei dados protegidos desta importação" hide-details /><v-btn color="primary" :disabled="!sensitiveConfirmed" :loading="acting" @click="resumeReview">Retomar revisão</v-btn>
      </template>
      <template v-else-if="needsWorkbookRecovery">
        <p class="eyebrow">Retomar os dados de origem</p><h2>Selecione novamente o mesmo workbook</h2><p>Para analisar ou alterar esta fonte, precisamos reler o mesmo arquivo. Os bytes não foram armazenados. O CoBudget conferirá o fingerprint e reaplicará apenas decisões compatíveis; a intenção protegida desta revisão continua válida no servidor.</p><v-file-input v-model="workbookInput" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" label="Mesmo workbook XLSX" prepend-icon="mdi-file-excel-outline" /><v-btn color="primary" :disabled="!selectedFile" :loading="acting" @click="recoverWorkbook">Continuar revisão</v-btn><v-btn variant="text" color="error" :disabled="acting" @click="abandonReview">Abandonar esta revisão</v-btn>
      </template>
      <template v-else-if="step===1">
        <p class="eyebrow">Dados de origem</p><h2>Selecione o workbook</h2><p>O arquivo permanece somente nesta sessão do navegador. A leitura identifica fontes conhecidas; ainda não cria itens financeiros.</p><v-checkbox v-model="sensitiveConfirmed" label="Entendo que acessarei dados protegidos nesta leitura" hide-details /><v-file-input v-model="workbookInput" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" label="Workbook XLSX" prepend-icon="mdi-file-excel-outline" :disabled="acting" /><div v-if="ownerSensitiveAccessNeeded" class="notice" role="status"><strong>Habilite o acesso protegido deste fechamento</strong><p>A confirmação acima registra sua intenção. Como proprietário, habilite a exceção temporária auditável antes de ler o workbook.</p><v-btn color="primary" size="small" :disabled="!sensitiveConfirmed" :loading="enablingOwnerSensitiveAccess" @click="enableOwnerSensitiveAccess">Habilitar leitura protegida</v-btn></div><v-btn color="primary" :disabled="!selectedFile||!sensitiveConfirmed" :loading="acting" @click="inventoryWorkbook">Identificar fontes</v-btn>
      </template>
      <template v-else-if="step===2 && configuringSheet && closing">
        <closing-source-profile-configuration :closing="closing" :sheet="configuringSheet" @saved="handleSourceProfileSaved" @cancel="configuringSheet=null" />
      </template>
      <template v-else-if="step===2 && !currentSheet">
        <p class="eyebrow">Fontes do workbook</p><h2>Confira o que entra neste lote</h2><p>Fontes com perfil compatível foram selecionadas. Abas novas ou ambíguas exigem configuração explícita e nunca entram silenciosamente.</p>
        <div v-if="alreadyPublishedSheets.length" class="published-list"><strong>Já importadas nesta competência</strong><p v-if="hasPartiallyImportedSources">Estas fontes permanecem no cálculo. Prepare apenas as fontes restantes.</p><ul><li v-for="sheet in alreadyPublishedSheets" :key="sheet.sheetName"><v-icon color="success">mdi-check-circle-outline</v-icon><div><strong>{{ sheet.sheetName }}</strong><small>Fonte confirmada com perfil e estrutura compatíveis. Ela não entrará novamente neste lote.</small></div></li></ul></div>
        <ul class="source-list"><li v-for="sheet in selectedSheets" :key="sheet.sheetName"><v-icon color="success">mdi-check-circle-outline</v-icon><div><strong>{{ sheet.sheetName }}</strong><small>{{ sheet.nonEmptyDataRows }} linha(s) materiais · {{ sheet.recommendedProfileName }}</small></div><v-btn size="small" variant="text" @click="excludeSheet(sheet.sheetName)">Não incluir</v-btn></li></ul>
        <div v-for="sheet in reviewSheets" :key="sheet.sheetName" class="notice" role="status"><strong>{{ sheet.sheetName }} {{ sheetStatus(sheet)==='STRUCTURE_CHANGED'?'teve a estrutura alterada':'precisa de revisão' }}</strong><p>{{ sheet.detail }} Nenhuma linha desta aba será preparada até a pendência indicada ser resolvida.</p><div class="inline-actions"><v-btn size="small" variant="tonal" @click="configureSheet(sheet)">{{ sheetStatus(sheet)==='STRUCTURE_CHANGED'?'Revisar perfil':'Configurar fonte e perfil' }}</v-btn><v-btn size="small" variant="text" @click="excludeSheet(sheet.sheetName)">Não incluir neste lote</v-btn></div></div>
        <div v-if="excludedSheets.length" class="muted-list"><strong>Fora deste lote</strong><span>{{ excludedSheets.join(', ') }}</span></div>
        <v-btn color="primary" :disabled="!selectedSheets.length" @click="beginSourceReview">Resolver fontes selecionadas</v-btn>
      </template>
      <template v-else-if="step===2 && currentSheet && closing">
        <div class="source-progress"><div><p class="eyebrow">Fonte {{ currentSourceIndex+1 }} de {{ selectedSheets.length }}</p><h2>{{ currentSheet.sheetName }}</h2></div><v-chip size="small" :color="currentSourceReady?'success':'warning'" variant="tonal">{{ currentSourceReady?'Pronta':'Em revisão' }}</v-chip></div>
        <guided-tabular-import-review :key="currentSheet.recommendedProfileId||currentSheet.sheetName" :closing="closing" :file="selectedFile" :profile-id="currentSheet.recommendedProfileId!" :workbook-review-id="review?.id" :sensitive-access-confirmed="sensitiveConfirmed" :participants="participants" :source-name="currentSheet.recommendedProfileName||currentSheet.sheetName" :sheet-name="currentSheet.sheetName" :ignored-sheets="excludedSheets" auto-start preparation-only @prepared="markSourcePrepared" @participant-created="loadParticipants" @profile-updated="refreshInventoryAfterProfile" @edit-profile-requested="configureSheet(currentSheet!)" />
        <div class="source-navigation"><v-btn v-if="currentSourceIndex>0" variant="text" @click="currentSourceIndex--">Fonte anterior</v-btn><v-btn v-if="currentSourceReady&&currentSourceIndex<selectedSheets.length-1" color="primary" @click="currentSourceIndex++">Próxima fonte</v-btn><v-btn v-else-if="allSourcesReady" color="primary" :loading="acting" @click="prepareSources">Preparar lote completo</v-btn></div>
      </template>
      <template v-else-if="step===3 && review?.status==='DRAFT'">
        <p class="eyebrow">Conferência</p><h2>Fontes preparadas</h2><p>O staging ainda está invisível ao cálculo. O preflight revalida versão, perfis, participantes, acesso e sobreposição.</p><dl class="summary"><div><dt>Fontes materializadas</dt><dd>{{ materializedCount }}/{{ review.selectedSourceCount }}</dd></div><div><dt>Itens preparados</dt><dd>{{ totalCandidates }}</dd></div><div><dt>Expiração do staging</dt><dd>{{ formatDate(review.stagingExpiresAt) }}</dd></div></dl><v-btn color="primary" :loading="acting" @click="runPreflight">Conferir importação</v-btn>
      </template>
      <template v-else-if="step===4 && review && ['PREFLIGHT_READY','PUBLISH_FAILED'].includes(review.status)">
        <p class="eyebrow">Confirmação única</p><h2>{{ review.status==='PUBLISH_FAILED'?'Retomar publicação':'Publicar lote' }}</h2><p>Esta confirmação cria os itens canônicos de todas as fontes em uma única transação. Não calcula, aprova nem cria obrigações.</p><div v-if="review.status==='PUBLISH_FAILED'" class="notice"><strong>A tentativa anterior não foi concluída</strong><p>Nenhum item parcial ficou visível. A mesma revisão pode ser retomada com segurança.</p></div><dl class="summary"><div><dt>Fontes</dt><dd>{{ preflight?.sourceCount ?? review.selectedSourceCount }}</dd></div><div><dt>Itens</dt><dd>{{ preflight?.itemCount ?? totalCandidates }}</dd></div><div><dt>Total de adições</dt><dd>{{ money(preflight?.additionTotal ?? totalAdditions) }}</dd></div><div><dt>Total de reversões</dt><dd>{{ money(preflight?.reversalTotal ?? totalReversals) }}</dd></div></dl><v-checkbox v-model="financialConfirmed" label="Confirmo a publicação financeira deste lote" hide-details /><v-btn color="primary" :disabled="!financialConfirmed" :loading="acting" @click="publish">Confirmar lote</v-btn>
      </template>
    </main>
    <div v-if="conflictNeedsAbandon" class="conflict-actions"><v-btn color="error" variant="tonal" @click="abandonReview">Abandonar revisão anterior</v-btn><v-btn variant="text" @click="backToPanel">Voltar ao painel</v-btn></div>
    <footer v-if="!published" class="sticky-action"><span>{{ stepHint }}</span><v-btn variant="text" @click="backToPanel">Salvar e sair</v-btn></footer>
  </div></div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useUserStore } from '@/plugins/userStore'
import AlertStrip from '@/components/AlertStrip.vue'
import GuidedTabularImportReview from '@/components/GuidedTabularImportReview.vue'
import ClosingSourceProfileConfiguration from '@/components/ClosingSourceProfileConfiguration.vue'
import FinancialClosingService,{type ClosingParticipant,type FinancialClosing,type GuidedImportReview,type ImportReadiness,type WorkbookInventory,type WorkbookPreflight,type WorkbookPublication,type WorkbookReview,type WorkbookReviewProgress,type WorkbookSheetInventory} from '@/services/FinancialClosingService'

const route=useRoute(),router=useRouter(),userStore=useUserStore();const closing=ref<FinancialClosing|null>(null),review=ref<WorkbookReview|null>(null),progress=ref<WorkbookReviewProgress|null>(null),inventory=ref<WorkbookInventory|null>(null),importReadiness=ref<ImportReadiness|null>(null),preflight=ref<WorkbookPreflight|null>(null),publication=ref<WorkbookPublication|null>(null),participants=ref<ClosingParticipant[]>([]),workbookInput=ref<File|File[]|null>(null),loading=ref(true),acting=ref(false),enablingOwnerSensitiveAccess=ref(false),errorMessage=ref(''),sensitiveConfirmed=ref(false),financialConfirmed=ref(false),resumed=ref(false),excludedNames=ref<string[]>([]),readyProfileIds=ref<string[]>([]),currentSourceIndex=ref(-1),conflictNeedsAbandon=ref(false),ownerSensitiveAccessNeeded=ref(false),configuringSheet=ref<WorkbookSheetInventory|null>(null)
const routeReviewId=computed(()=>String(route.params.reviewId||'new'));const selectedFile=computed(()=>Array.isArray(workbookInput.value)?workbookInput.value[0]||null:workbookInput.value);const importedSourceKeys=computed(()=>new Set((importReadiness.value?.sources||[]).filter(source=>source.status==='IMPORTED').map(source=>source.sourceKey)));const alreadyPublishedSheets=computed(()=>inventory.value?.sheets.filter(sheet=>sheet.selectionStatus==='AUTO_SELECTED'&&sheet.recommendedProfileId&&importedSourceKeys.value.has(sheet.suggestedSourceKey))||[]);const selectedSheets=computed(()=>inventory.value?.sheets.filter(sheet=>sheet.selectionStatus==='AUTO_SELECTED'&&sheet.recommendedProfileId&&!importedSourceKeys.value.has(sheet.suggestedSourceKey)&&!excludedNames.value.includes(sheet.sheetName))||[]);const reviewSheets=computed(()=>inventory.value?.sheets.filter(sheet=>sheet.selectionStatus==='REVIEW_REQUIRED'&&!excludedNames.value.includes(sheet.sheetName))||[]);const excludedSheets=computed(()=>inventory.value?.sheets.filter(sheet=>excludedNames.value.includes(sheet.sheetName)).map(sheet=>sheet.sheetName)||[]);const currentSheet=computed(()=>currentSourceIndex.value>=0?selectedSheets.value[currentSourceIndex.value]||null:null);const currentSourceReady=computed(()=>Boolean(currentSheet.value?.recommendedProfileId&&readyProfileIds.value.includes(currentSheet.value.recommendedProfileId)));const allSourcesReady=computed(()=>selectedSheets.value.length>0&&selectedSheets.value.every(sheet=>readyProfileIds.value.includes(sheet.recommendedProfileId!)));const hasPartiallyImportedSources=computed(()=>alreadyPublishedSheets.value.length>0&&selectedSheets.value.length+reviewSheets.value.length>0)
const published=computed(()=>review.value?.status==='PUBLISHED'||progress.value?.status==='PUBLISHED'||Boolean(publication.value));const expiredReview=computed(()=>progress.value?.reviewExpired||review.value?.status==='EXPIRED');const needsResumeIntent=computed(()=>routeReviewId.value!=='new'&&!published.value&&!expiredReview.value&&!resumed.value);const stagingExpired=computed(()=>progress.value?.stagingExpired||Boolean(review.value&&new Date(review.value.stagingExpiresAt)<=new Date()));const materializedCount=computed(()=>review.value?.sources.filter(source=>['MATERIALIZED','PUBLISHED'].includes(source.status)).length||0);const reviewNeedsWorkbook=computed(()=>Boolean(review.value&&!['PREFLIGHT_READY','PUBLISH_FAILED'].includes(review.value.status)));const needsWorkbookRecovery=computed(()=>Boolean(reviewNeedsWorkbook.value&&!published.value&&!needsResumeIntent.value&&!selectedFile.value));const totalCandidates=computed(()=>review.value?.sources.reduce((sum,source)=>sum+source.candidateCount,0)||0);const totalAdditions=computed(()=>review.value?.sources.reduce((sum,source)=>sum+source.additionTotal,0)||0);const totalReversals=computed(()=>review.value?.sources.reduce((sum,source)=>sum+source.reversalTotal,0)||0)
const step=computed(()=>published.value?4:review.value&&['PREFLIGHT_READY','PUBLISH_FAILED'].includes(review.value.status)?4:review.value&&review.value.selectedSourceCount>0?3:inventory.value?2:1);const competenceLabel=computed(()=>closing.value?`${String(closing.value.periodMonth).padStart(2,'0')}/${closing.value.periodYear} · ${closing.value.closingKey}`:'Apuração');const stepHint=computed(()=>['','Selecione o arquivo uma vez nesta sessão.','Resolva uma fonte por vez.','O staging ainda não afeta o cálculo.','A publicação é atômica e idempotente.'][step.value])
function clearWorkbook(){workbookInput.value=null;sensitiveConfirmed.value=false}
async function initialize(){loading.value=true;try{const all=(await FinancialClosingService.list()).data;closing.value=all.find(item=>item.id===String(route.params.closingId))||null;if(!closing.value)throw new Error('missing closing');await Promise.all([loadParticipants(),loadImportReadiness()]);if(routeReviewId.value!=='new'){progress.value=(await FinancialClosingService.workbookReviewProgress(closing.value.id,routeReviewId.value)).data;if(progress.value.status==='PUBLISHED'){review.value={...progress.value,preflightHmac:null,sources:[]} as WorkbookReview;resumed.value=true}else{try{inventory.value=(await FinancialClosingService.workbookReviewInventory(closing.value.id,routeReviewId.value)).data;review.value=(await FinancialClosingService.workbookReview(closing.value.id,routeReviewId.value)).data;resumed.value=true}catch(error:any){if(error?.response?.status!==403)throw error}}}}catch{errorMessage.value='Não foi possível abrir esta revisão no workspace atual.'}finally{loading.value=false}}
async function loadParticipants(){if(closing.value)participants.value=(await FinancialClosingService.participants(closing.value)).data}
async function loadImportReadiness(){if(!closing.value)return;try{importReadiness.value=(await FinancialClosingService.importReadiness(closing.value)).data}catch{importReadiness.value=null}}
async function resumeReview(){if(!closing.value)return;acting.value=true;errorMessage.value='';try{await FinancialClosingService.confirmWorkbookSensitiveIntent(closing.value.id,routeReviewId.value);review.value=(await FinancialClosingService.workbookReview(closing.value.id,routeReviewId.value)).data;progress.value=(await FinancialClosingService.workbookReviewProgress(closing.value.id,routeReviewId.value)).data;try{inventory.value=(await FinancialClosingService.workbookReviewInventory(closing.value.id,routeReviewId.value)).data}catch{inventory.value=null}resumed.value=true}catch{errorMessage.value='O acesso expirou, foi revogado ou a revisão não está mais disponível.'}finally{acting.value=false}}
async function inventoryWorkbook(preserveJourney=false){if(!closing.value||!selectedFile.value)return;acting.value=true;errorMessage.value='';ownerSensitiveAccessNeeded.value=false;try{const response=(await FinancialClosingService.initiateWorkbookReview(closing.value,selectedFile.value,true)).data;review.value=response.review;progress.value=null;inventory.value=response.inventory;resumed.value=true;await loadImportReadiness();currentSourceIndex.value=-1;if(!preserveJourney){readyProfileIds.value=[];excludedNames.value=[]}else{const currentProfileIds=new Set(response.inventory.sheets.map(sheet=>sheet.recommendedProfileId).filter(Boolean));readyProfileIds.value=readyProfileIds.value.filter(id=>currentProfileIds.has(id));excludedNames.value=excludedNames.value.filter(name=>response.inventory.sheets.some(sheet=>sheet.sheetName===name))}await router.replace({name:'closing-import-wizard',params:{closingId:closing.value.id,reviewId:review.value.id}});if(!selectedSheets.value.length&&!reviewSheets.value.length&&!alreadyPublishedSheets.value.length)errorMessage.value='Nenhuma fonte está pendente para importar nesta competência.'}catch(error:any){const owner=userStore.getTenantRole==='ROLE_OWNER';ownerSensitiveAccessNeeded.value=owner&&error?.response?.status===403;errorMessage.value=error?.response?.status===409?'Já existe uma revisão ativa para outro workbook. Retome-a ou abandone-a antes de continuar.':ownerSensitiveAccessNeeded.value?'A leitura exige acesso protegido para este fechamento. Habilite a exceção temporária abaixo e tente novamente.':'Não foi possível ler o workbook. O arquivo não foi armazenado.'}finally{acting.value=false}}
async function enableOwnerSensitiveAccess(){if(!closing.value||!sensitiveConfirmed.value||!userStore.getUser?.id)return;enablingOwnerSensitiveAccess.value=true;errorMessage.value='';try{await FinancialClosingService.grantSensitiveAccess(closing.value,userStore.getUser.id,true);ownerSensitiveAccessNeeded.value=false;errorMessage.value='Acesso protegido habilitado para este fechamento. Agora identifique as fontes do workbook.'}catch{errorMessage.value='Não foi possível habilitar o acesso protegido deste fechamento.'}finally{enablingOwnerSensitiveAccess.value=false}}
function beginSourceReview(){currentSourceIndex.value=0}function excludeSheet(name:string){if(!excludedNames.value.includes(name))excludedNames.value=[...excludedNames.value,name];if(currentSourceIndex.value>=selectedSheets.value.length)currentSourceIndex.value=Math.max(-1,selectedSheets.value.length-1)}function markSourcePrepared(_:GuidedImportReview){const id=currentSheet.value?.recommendedProfileId;if(id&&!readyProfileIds.value.includes(id))readyProfileIds.value=[...readyProfileIds.value,id]}function sheetStatus(sheet:WorkbookSheetInventory){if(excludedNames.value.includes(sheet.sheetName))return 'EXCLUDED';if(sheet.selectionStatus==='CONSOLIDATION')return 'REFERENCE_ONLY';if(sheet.selectionStatus==='AUTO_SELECTED'&&importedSourceKeys.value.has(sheet.suggestedSourceKey))return 'ALREADY_PUBLISHED';if(sheet.selectionStatus==='AUTO_SELECTED')return 'READY_TO_PREPARE';return sheet.reviewReason||'CONFIGURATION_REQUIRED'}function configureSheet(sheet:WorkbookSheetInventory){configuringSheet.value=sheet;currentSourceIndex.value=-1}async function handleSourceProfileSaved(_:string){configuringSheet.value=null;if(selectedFile.value)await inventoryWorkbook(true);else errorMessage.value='O perfil foi salvo. Selecione novamente o mesmo workbook para atualizar o inventário desta revisão.'}
async function prepareSources(){if(!closing.value||!selectedFile.value||!allSourcesReady.value||!review.value)return;acting.value=true;errorMessage.value='';conflictNeedsAbandon.value=false;try{review.value=(await FinancialClosingService.prepareWorkbookReview(closing.value,selectedFile.value,selectedSheets.value.map(sheet=>sheet.recommendedProfileId!),review.value.id)).data;progress.value=null;resumed.value=true}catch(error:any){if(error?.response?.status===409){errorMessage.value='O arquivo ou a seleção não corresponde à revisão retomada. Decisões anteriores não foram reaproveitadas.';conflictNeedsAbandon.value=true}else errorMessage.value='Ainda existem pendências em uma das fontes. Nenhum item foi publicado.'}finally{acting.value=false}}
async function recoverStaging(){if(!closing.value||!selectedFile.value||!review.value)return;acting.value=true;errorMessage.value='';try{inventory.value=(await FinancialClosingService.workbookInventory(closing.value,selectedFile.value,true)).data;const selectedKeys=new Set(review.value.sources.map(source=>source.sourceKey));const profiles=inventory.value.sheets.filter(sheet=>sheet.selectionStatus==='AUTO_SELECTED'&&sheet.recommendedProfileId&&selectedKeys.has(sheet.suggestedSourceKey)).map(sheet=>sheet.recommendedProfileId!);if(profiles.length!==review.value.selectedSourceCount)throw {response:{status:409}};review.value=(await FinancialClosingService.prepareWorkbookReview(closing.value,selectedFile.value,profiles,routeReviewId.value)).data;progress.value=(await FinancialClosingService.workbookReviewProgress(closing.value.id,routeReviewId.value)).data}catch(error:any){errorMessage.value=error?.response?.status===409?'Este não é o mesmo workbook ou a seleção de fontes mudou. Nenhuma decisão foi reaplicada.':'Não foi possível reconstruir o staging.';conflictNeedsAbandon.value=error?.response?.status===409}finally{acting.value=false}}
async function recoverWorkbook(){if(review.value?.selectedSourceCount===0){await inventoryWorkbook(true);return}await recoverStaging()}
async function runPreflight(){if(!closing.value||!review.value)return;acting.value=true;errorMessage.value='';try{preflight.value=(await FinancialClosingService.preflightWorkbookReview(closing.value.id,review.value.id,review.value.revision)).data;review.value=(await FinancialClosingService.workbookReview(closing.value.id,review.value.id)).data}catch(error:any){errorMessage.value=error?.response?.status===403?'A autorização sensível expirou ou foi revogada. Retome a revisão antes de continuar.':error?.response?.status===409?'A preparação mudou ou expirou. Atualize a revisão antes de publicar.':'Não foi possível concluir a conferência.'}finally{acting.value=false}}
async function publish(){if(!closing.value||!review.value||!review.value.preflightHmac)return;acting.value=true;errorMessage.value='';try{const storageKey=`closing-workbook-publication:${review.value.id}`;let key=sessionStorage.getItem(storageKey);if(!key){key=crypto.randomUUID();sessionStorage.setItem(storageKey,key)}publication.value=(await FinancialClosingService.publishWorkbookReview(closing.value.id,review.value.id,{expectedRevision:review.value.revision,preflightHmac:review.value.preflightHmac,idempotencyKey:key})).data;review.value=(await FinancialClosingService.workbookReview(closing.value.id,review.value.id)).data;clearWorkbook()}catch(error:any){errorMessage.value=error?.response?.status===403?'A autorização sensível expirou ou foi revogada. Retome antes de publicar.':error?.response?.status===409?'O preflight ficou desatualizado. Reabra a conferência antes de tentar novamente.':'A publicação não foi concluída; nenhum item parcial ficou visível.'}finally{acting.value=false}}
async function abandonReview(){if(!closing.value||!review.value)return;acting.value=true;try{await FinancialClosingService.abandonWorkbookReview(closing.value.id,review.value.id,review.value.revision);startNewReview()}catch{errorMessage.value='A revisão mudou ou já é terminal. Atualize o painel antes de abandonar.'}finally{acting.value=false}}
function startNewReview(){router.replace({name:'closing-import-wizard',params:{closingId:closing.value?.id,reviewId:'new'}});review.value=null;progress.value=null;inventory.value=null;clearWorkbook();resumed.value=false;conflictNeedsAbandon.value=false;ownerSensitiveAccessNeeded.value=false;configuringSheet.value=null}
async function refreshInventoryAfterProfile(){if(selectedFile.value)await inventoryWorkbook(true)}
function backToPanel(){clearWorkbook();router.push({name:'planning-financial-closings',query:{closingId:closing.value?.id}})}function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)}function formatDate(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}onMounted(initialize);onBeforeUnmount(clearWorkbook);watch(()=>routeReviewId.value,()=>{if(routeReviewId.value!=='new'&&!review.value)void initialize()});watch(()=>[userStore.getCurrentWorkspaceId,userStore.isAuthenticated] as const,([workspaceId,authenticated])=>{if(!authenticated||workspaceId!==closing.value?.workspaceId)clearWorkbook()})
</script>

<style scoped>
.import-wizard{min-height:100vh;background:var(--cb-surface-soft,#f6f7fb);padding:20px}.wizard-shell{max-width:900px;margin:0 auto}.wizard-header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:16px;margin-bottom:14px}.wizard-header h1,.source-progress h2{font-size:1.45rem;margin:2px 0}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.72rem;color:var(--cb-text-muted,#667085);margin:0}.wizard-card{margin-top:18px;padding:28px;display:grid;gap:18px}.wizard-card h2{font-size:1.5rem;margin:0}.wizard-card>p{color:var(--cb-text-muted,#667085);margin:0}.wizard-state{display:grid;place-items:center}.source-list,.published-list ul{list-style:none;padding:0;display:grid;gap:10px}.source-list li,.published-list li{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:12px;padding:14px;background:#f7f8fb;border-radius:10px}.source-list small,.published-list small{display:block;color:var(--cb-text-muted,#667085)}.published-list{display:grid;gap:5px;padding:14px;border:1px solid #b7ebc6;border-radius:10px;background:#f0fdf4}.published-list p{margin:0;color:var(--cb-text-muted,#667085)}.notice{padding:14px;border-left:4px solid #b7791f;background:#fffaf0}.notice p{margin:4px 0}.inline-actions,.source-navigation,.conflict-actions{display:flex;gap:8px;flex-wrap:wrap}.muted-list{display:grid;gap:4px;color:var(--cb-text-muted,#667085)}.source-progress{display:flex;justify-content:space-between;align-items:center;gap:12px}.source-navigation{justify-content:flex-end}.summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.summary div{padding:14px;background:#f7f8fb;border-radius:10px}.summary dt{color:var(--cb-text-muted,#667085);font-size:.85rem}.summary dd{font-weight:700;margin:5px 0 0}.conflict-actions{justify-content:center;padding:12px}.sticky-action{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0;color:var(--cb-text-muted,#667085)}@media(max-width:600px){.import-wizard{padding:12px 12px 96px}.wizard-header{grid-template-columns:1fr auto}.wizard-header>.v-btn{grid-column:1/-1;justify-self:start}.wizard-card{padding:18px 16px}.summary{grid-template-columns:1fr}.wizard-card>.v-btn,.source-navigation>.v-btn,.inline-actions>.v-btn{width:100%;min-height:48px}.source-list li,.published-list li{grid-template-columns:auto 1fr}.source-list li>.v-btn{grid-column:1/-1}.source-navigation,.inline-actions{flex-direction:column}.sticky-action{position:fixed;left:0;right:0;bottom:0;background:white;border-top:1px solid #e7e9ef;padding:10px 12px calc(10px + env(safe-area-inset-bottom));z-index:5}.sticky-action span{font-size:.78rem;max-width:60%}}
</style>
