<template>
  <section class="guided-review" aria-labelledby="guided-review-title">
    <div class="guided-review__heading">
      <div><p class="eyebrow">Revisão assistida</p><h3 id="guided-review-title">Preparar esta importação</h3></div>
      <v-chip v-if="review" size="small" :color="review.readyForConfirmation ? 'success' : 'warning'" variant="tonal">{{ review.readyForConfirmation ? (preparationOnly ? 'Pronta para o lote' : 'Pronta para confirmar') : 'Há decisões pendentes' }}</v-chip>
    </div>
    <p>O CoBudget organiza as exceções. Nada entra no fechamento antes da sua confirmação final.</p>
    <v-btn color="primary" variant="tonal" :loading="loading" :disabled="!file || !profileId || !sensitiveAccessConfirmed" @click="openReview">{{ review ? 'Atualizar revisão final' : 'Analisar e iniciar revisão' }}</v-btn>
    <p v-if="message" class="guided-review__message" role="status">{{ message }}</p>

    <template v-if="review">
      <div class="guided-review__sticky" role="region" aria-label="Próxima ação da importação">
        <div><strong>{{ review.readyForConfirmation ? (preparationOnly ? 'Fonte pronta para o lote' : 'Pronta para confirmar') : 'Revisão em andamento' }}</strong><small v-if="!review.readyForConfirmation">{{ review.blockingReasons[0] || 'Aguardando as decisões indicadas abaixo.' }}</small><small v-else>{{ review.summary.importableRows }} linha(s) · {{ money(review.summary.importableTotal) }}</small></div>
        <template v-if="review.readyForConfirmation && preparationOnly"><v-icon color="success" icon="mdi-check-circle-outline" /><span>A confirmação financeira será única para todo o workbook.</span></template>
        <template v-else-if="review.readyForConfirmation"><v-checkbox v-model="financialConfirmation" label="Confirmo o efeito financeiro" hide-details /><v-btn color="primary" :loading="confirming" :disabled="!financialConfirmation" @click="confirmReview">Confirmar importação</v-btn></template>
        <template v-else><v-btn v-if="blockerAction(review.blockingReasons[0])" color="primary" variant="tonal" @click="resolveBlocker(review.blockingReasons[0])">{{ blockerAction(review.blockingReasons[0])?.label }}</v-btn><v-btn variant="text" :loading="loading" @click="openReview">Revalidar</v-btn></template>
      </div>
      <div v-if="review.alreadyConfirmed" class="guided-review__notice" role="status"><strong>Este arquivo já foi confirmado.</strong><p>O resultado anterior será reutilizado; nenhum item será criado novamente.</p></div>

      <article v-if="review.monetaryFormat" ref="monetarySection" class="guided-review__step">
        <h4>1. Conferir o formato dos valores</h4>
        <div class="guided-review__item">
          <div><strong>{{ monetaryFormatLabel(review.monetaryFormat) }}</strong><small>{{ review.monetaryFormat.acceptedValues }} de {{ review.monetaryFormat.observedValues }} valor(es) reconhecido(s) · {{ review.monetaryFormat.rejectedValues }} exceção(ões)</small></div>
          <v-chip size="x-small" :color="review.monetaryFormat.confidence === 'HIGH' ? 'success' : 'warning'" variant="tonal">{{ review.monetaryFormat.confidence === 'HIGH' ? 'Confiança alta' : 'Precisa de revisão' }}</v-chip>
          <p v-if="review.monetaryFormat.nativeNumericCanonical">Os valores numéricos do Excel são usados diretamente. Símbolo e separadores são apenas a apresentação encontrada na planilha.</p>
          <p v-if="review.monetaryFormat.textualValues > 0">Para as {{ review.monetaryFormat.textualValues }} célula(s) textual(is), esta é uma sugestão desta revisão. O perfil reutilizável não será alterado sem uma ação separada.</p>
          <p v-if="review.monetaryFormat.selected" class="guided-review__message">Formato escolhido para este lote<span v-if="review.monetaryFormat.savedAsProfile"> e salvo como novo padrão da fonte</span>.</p>
          <div v-if="review.monetaryFormat.decisionKey" class="guided-review__actions">
            <v-btn v-if="review.monetaryFormat.requiresDecision" size="small" color="primary" variant="tonal" :disabled="saving" @click="useMonetaryFormat(false)">Usar somente neste lote</v-btn>
            <v-btn size="small" variant="text" :disabled="saving || review.monetaryFormat.savedAsProfile" @click="useMonetaryFormat(true)">Salvar como padrão desta fonte</v-btn>
          </div>
        </div>
      </article>

      <article v-if="review.participants.length" ref="participantsSection" class="guided-review__step">
        <h4>2. Quem recebe estes valores?</h4>
        <p>O CoBudget encontrou uma coluna de responsável ou beneficiário. Confirme se ela representa quem participa desta apuração.</p>
        <v-checkbox v-model="participantColumnConfirmed" label="Sim, esta coluna identifica o participante ou beneficiário da apuração" hide-details />
        <p v-if="participantColumnConfirmed">Ela contém <strong>{{ review.participants.length }} grupo(s)</strong> em <strong>{{ review.summary.participantOccurrences }} ocorrência(s)</strong>. Revise um grupo por vez; nenhuma sugestão é aplicada automaticamente.</p>
        <div v-for="group in participantColumnConfirmed ? review.participants : []" :key="group.decisionKey" class="guided-review__item">
          <div><strong>{{ group.sourceLabel }}</strong><small>{{ group.occurrenceCount }} ocorrência(s)</small><small v-if="group.participantId" class="guided-review__association">Associado a {{ participantName(group.participantId) }}</small></div>
          <v-chip size="x-small" :color="group.blocking ? 'warning' : 'success'" variant="tonal">{{ participantResolutionLabel(group.resolution) }}</v-chip>
          <div v-if="group.suggestions.length" class="guided-review__suggestions"><span>Sugestões para sua revisão:</span><v-btn v-for="suggestion in group.suggestions" :key="suggestion.participantId" size="x-small" variant="tonal" :disabled="saving" @click="linkParticipant(group.decisionKey, suggestion.participantId)">{{ suggestion.displayName }} · {{ suggestion.confidence }}%</v-btn></div>
          <div class="guided-review__actions"><v-select v-model="participantSelections[group.decisionKey]" :items="participantOptions" :label="group.participantId ? 'Associar a outro participante' : 'Escolher participante existente'" hide-details /><v-btn size="small" variant="tonal" :disabled="!participantSelections[group.decisionKey] || saving" :loading="saving" @click="linkParticipant(group.decisionKey, participantSelections[group.decisionKey])">{{ group.participantId ? 'Alterar associação' : 'Associar' }}</v-btn><v-btn size="small" variant="text" :disabled="saving" @click="createParticipant(group)">Criar participante com este nome</v-btn><v-btn size="small" variant="text" :disabled="saving" @click="markExternalCreditor(group.decisionKey)">É um credor externo</v-btn><v-btn size="small" variant="text" :disabled="saving" @click="leavePending(group.decisionKey)">Retomar depois</v-btn></div>
          <p v-if="group.resolution === 'EXTERNAL_CREDITOR'" class="guided-review__warning">Credores externos não recebem Produtividade. Este grupo fica identificado, mas ainda bloqueia esta importação.</p>
        </div>
      </article>

      <article v-if="review.repetitions.length" ref="repetitionsSection" class="guided-review__step">
        <h4>3. Revisar referências repetidas</h4>
        <p>Foram encontrados <strong>{{ review.repetitions.length }} grupo(s)</strong>, com <strong>{{ review.summary.repetitionOccurrences }} ocorrência(s)</strong> e impacto agregado de <strong>{{ money(repetitionTotal) }}</strong>.</p>
        <details class="guided-review__details"><summary>Ver grupos repetidos</summary><ul><li v-for="(group,index) in review.repetitions" :key="`${group.decisionKey}-${index}`"><strong>Grupo {{ index + 1 }}</strong> · {{ group.occurrenceCount }} ocorrências · impacto {{ money(group.aggregateAmount) }}</li></ul></details>
        <div v-if="review.repetitionsAccepted" class="guided-review__success" role="status"><v-icon icon="mdi-check-circle" size="small" /> Repetições revisadas e confirmadas para este lote.</div>
        <div v-else class="guided-review__actions"><v-select v-model="repetitionReason" :items="repetitionReasons" label="Motivo revisado" hide-details /><v-text-field v-model="repetitionNote" label="Complemento opcional" hide-details /><v-btn size="small" color="primary" variant="tonal" :disabled="!repetitionReason || saving" @click="acceptRepetitions(review.repetitions[0].decisionKey)">Estas repetições são itens distintos e devem ser mantidas</v-btn></div>
      </article>

      <article v-if="review.zeroAmountGroup" class="guided-review__step">
        <h4>4. Linhas sem valor financeiro</h4>
        <p><strong>{{ review.zeroAmountGroup.occurrenceCount }} linha(s)</strong> têm valor R$ 0,00 e não geram efeito financeiro. Você pode deixá-las fora deste lote com uma única decisão auditada.</p>
        <div v-if="review.zeroAmountGroup.excluded" class="guided-review__success" role="status"><v-icon icon="mdi-check-circle" size="small" /> Linhas de valor zero ignoradas neste lote.</div>
        <div v-else class="guided-review__actions"><v-text-field v-model="zeroAmountJustification" label="Justificativa para ignorar as linhas de valor zero" hide-details /><v-btn size="small" color="primary" variant="tonal" :disabled="!zeroAmountJustification.trim() || saving" @click="excludeZeroAmountRows(review.zeroAmountGroup.decisionKey)">Ignorar todas as linhas de valor zero</v-btn></div>
      </article>

      <article v-if="review.pendingRows.length" ref="pendingRowsSection" class="guided-review__step">
        <h4>5. Pendências deste lote</h4>
        <p>Linhas abaixo continuam fora da confirmação até serem corrigidas ou excluídas. A planilha original não será alterada.</p>
        <div v-if="review.dateAlternatives?.length" class="guided-review__notice"><strong>Outra coluna de data pode resolver pendências</strong><p>O resultado abaixo foi testado somente nesta prévia. Escolher uma opção não altera a planilha nem o perfil salvo.</p><div class="guided-review__actions"><v-btn v-for="option in review.dateAlternatives" :key="option.decisionKey" size="small" variant="tonal" :disabled="saving" @click="useDateColumn(option)">Usar “{{ option.columnLabel }}” · resolve {{ option.resolvedRows }} linha(s)</v-btn></div></div>
        <div v-for="row in review.pendingRows" :key="row.decisionKey" class="guided-review__item">
          <div><strong>Linha {{ row.rowNumber }}</strong><small>{{ issueLabel(row.issueType) }} · {{ rowResolutionLabel(row.resolution) }}</small></div>
          <div v-if="row.resolution === 'EXCLUDE_ROW'" class="guided-review__success" role="status"><v-icon icon="mdi-check-circle" size="small" /> Exclusão confirmada e auditada para este lote.</div>
          <template v-else><div class="guided-review__actions"><v-text-field v-if="row.issueType.includes('AMOUNT')" v-model.number="rowAmounts[row.decisionKey]" type="number" min="0.01" step="0.01" label="Valor correto para este lote" hide-details /><v-text-field v-if="row.issueType.includes('DATE')" v-model="rowDates[row.decisionKey]" type="date" label="Data correta para este lote" hide-details /><v-btn v-if="row.issueType.includes('AMOUNT')" size="small" variant="tonal" :disabled="!rowAmounts[row.decisionKey] || saving" @click="correctAmount(row)">Usar este valor</v-btn><v-btn v-if="row.issueType.includes('DATE')" size="small" variant="tonal" :disabled="!rowDates[row.decisionKey] || saving" @click="correctDate(row)">Usar esta data</v-btn></div>
          <div class="guided-review__actions"><v-text-field v-model="rowJustifications[row.decisionKey]" label="Justificativa para excluir" hide-details /><v-btn size="small" color="error" variant="text" :disabled="!rowJustifications[row.decisionKey]?.trim() || saving" @click="excludeRow(row)">Excluir deste fechamento</v-btn></div></template>
        </div>
      </article>

      <article class="guided-review__step guided-review__summary">
        <h4>6. Revisão final</h4>
        <p><strong>Incluída:</strong> {{ sourceName }}<span v-if="sheetName"> · aba “{{ sheetName }}”</span>.</p><p v-if="ignoredSheets.length"><strong>Ignoradas:</strong> {{ ignoredSheets.join(', ') }} — permanecem fora do cálculo.</p>
        <dl><div><dt>Linhas lidas</dt><dd>{{ review.summary.rowsRead }}</dd></div><div><dt>Ignoradas com segurança</dt><dd>{{ review.summary.structurallyIgnored }}</dd></div><div><dt>Ignoradas sem destinatário</dt><dd>{{ review.summary.ignoredWithoutRecipientRows }} · {{ money(review.summary.ignoredWithoutRecipientTotal) }}</dd></div><div><dt>Corrigidas nesta revisão</dt><dd>{{ review.summary.correctedRows }}</dd></div><div><dt>Excluídas por decisão</dt><dd>{{ review.summary.excludedRows }}</dd></div><div><dt>Prontas para importar</dt><dd>{{ review.summary.importableRows }}</dd></div><div><dt>Total importável</dt><dd>{{ money(review.summary.importableTotal) }}</dd></div></dl>
        <ul v-if="review.blockingReasons.length" class="guided-review__blocks" role="alert"><li v-for="reason in review.blockingReasons" :key="reason"><span>{{ reason }}</span><v-btn v-if="blockerAction(reason)" size="small" variant="tonal" @click="resolveBlocker(reason)">{{ blockerAction(reason)?.label }}</v-btn></li></ul>
        <p v-if="!review.readyForConfirmation" class="guided-review__message">As decisões são revalidadas automaticamente. Resolva somente as pendências indicadas acima.</p>
      </article>

    </template>
  </section>
</template>

<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import FinancialClosingService, { type ClosingParticipant, type FinancialClosing, type GuidedImportReview, type GuidedParticipantGroup, type GuidedPendingRow } from '@/services/FinancialClosingService'

const props=withDefaults(defineProps<{closing:FinancialClosing;file:File|null;profileId:string;sensitiveAccessConfirmed:boolean;participants:ClosingParticipant[];workbookReviewId?:string;sourceName?:string;sheetName?:string;ignoredSheets?:string[];autoStart?:boolean;preparationOnly?:boolean}>(),{sourceName:'Fonte selecionada',sheetName:'',ignoredSheets:()=>[],autoStart:false,preparationOnly:false})
const emit=defineEmits<{confirmed:[];prepared:[review:GuidedImportReview];reviewState:[ready:boolean];participantCreated:[];profileUpdated:[];editProfileRequested:[]}>()
const review=ref<GuidedImportReview|null>(null);const loading=ref(false);const saving=ref(false);const confirming=ref(false);const message=ref('');const financialConfirmation=ref(false);const participantColumnConfirmed=ref(false);const participantSelections=reactive<Record<string,string>>({});const rowAmounts=reactive<Record<string,number|null>>({});const rowDates=reactive<Record<string,string>>({});const rowJustifications=reactive<Record<string,string>>({});const repetitionReason=ref('');const repetitionNote=ref('');const zeroAmountJustification=ref('')
const monetarySection=ref<HTMLElement|null>(null);const participantsSection=ref<HTMLElement|null>(null);const repetitionsSection=ref<HTMLElement|null>(null);const pendingRowsSection=ref<HTMLElement|null>(null)
const repetitionReasons=[{title:'A fonte registra itens distintos com a mesma referência',value:'SOURCE_CONFIRMED_DISTINCT'},{title:'O documento operacional comprova ocorrências separadas',value:'OPERATIONAL_EVIDENCE'},{title:'Outro motivo revisado',value:'OTHER_REVIEWED_REASON'}]
const participantOptions=computed(()=>props.participants.filter(item=>item.active).map(item=>({title:item.displayName,value:item.id})))
function participantName(id:string){return props.participants.find(item=>item.id===id)?.displayName||'participante registrado'}
const repetitionTotal=computed(()=>review.value?.repetitions.reduce((total,item)=>total+Number(item.aggregateAmount||0),0)||0)
function eventKey(){return crypto.randomUUID()}
async function openReview(){if(!props.file||!props.profileId)return false;if(loading.value)return false;loading.value=true;message.value='';try{review.value=(await FinancialClosingService.startGuidedImportReview(props.closing,props.file,props.profileId,props.sensitiveAccessConfirmed,props.workbookReviewId)).data;for(const group of review.value.participants)if(group.participantId&&!participantSelections[group.decisionKey])participantSelections[group.decisionKey]=group.participantId;financialConfirmation.value=false;emit('reviewState',review.value.readyForConfirmation);message.value=review.value.readyForConfirmation?(props.preparationOnly?'Fonte pronta. Ela continuará invisível ao cálculo até a confirmação única do workbook.':'Revisão concluída. Confira o resumo antes de confirmar.'):'As decisões pendentes foram organizadas abaixo.';if(review.value.readyForConfirmation&&props.preparationOnly)emit('prepared',review.value);return true}catch(error:any){message.value=error?.response?.status===403?'Seu acesso a dados protegidos não está autorizado neste espaço.':'Não foi possível preparar a revisão. Confirme o perfil e o arquivo selecionados.';return false}finally{loading.value=false}}
async function save(decision:Record<string,unknown>){if(!review.value||saving.value)return false;saving.value=true;message.value='';try{if(!await openReview())return false;if(!review.value)return false;const response=await FinancialClosingService.saveGuidedReviewDecision(props.closing,review.value.reviewId,{eventKey:eventKey(),expectedRevision:review.value.revision,reviewSourceId:review.value.reviewSourceId,...decision} as any);review.value.revision=response.data.revision;message.value='Decisão salva. Ela será revalidada no resumo final.';return true}catch(error:any){if(error?.response?.status===409){saving.value=false;await openReview();message.value='A revisão foi atualizada. Repita somente a decisão que você acabou de tentar.'}else message.value='Não foi possível salvar esta decisão.';return false}finally{saving.value=false}}
async function refreshAfterDecision(success:string){if(await openReview())message.value=success}
async function linkParticipant(decisionKey:string,participantId:string){if(await save({decisionKey,action:'LINK_PARTICIPANT',participantId,reasonCode:'EXPLICIT_ASSOCIATION',justification:'Associação explícita feita na revisão protegida'}))await refreshAfterDecision('Participante associado e revisão atualizada.')}
function safeKey(label:string){return label.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9]+/g,'_').replace(/^_|_$/g,'').toUpperCase().slice(0,80)||`PARTICIPANT_${Date.now()}`}
async function createParticipant(group:GuidedParticipantGroup){if(await save({decisionKey:group.decisionKey,action:'CREATE_PARTICIPANT',participantKey:safeKey(group.sourceLabel),displayName:group.sourceLabel,reasonCode:'EXPLICIT_CREATION',justification:'Criação confirmada a partir da prévia protegida'})){emit('participantCreated');await refreshAfterDecision('Participante criado, associado e revisão atualizada.')}}
async function markExternalCreditor(decisionKey:string){if(await save({decisionKey,action:'EXTERNAL_CREDITOR',reasonCode:'EXTERNAL_PARTY',justification:'Classificado explicitamente como credor externo'}))await refreshAfterDecision('Credor externo identificado. A pendência permanece visível porque não gera Produtividade.')}
async function leavePending(decisionKey:string){if(await save({decisionKey,action:'PENDING',reasonCode:'REVIEW_LATER',justification:'Operador decidiu retomar este grupo depois'}))await refreshAfterDecision('Grupo mantido como pendente para revisão posterior.')}
async function acceptRepetitions(decisionKey:string){if(await save({decisionKey,action:'ACCEPT_DISTINCT_ITEMS',reasonCode:repetitionReason.value,justification:repetitionNote.value.trim()||'Ocorrências revisadas em lote pelo operador'}))await refreshAfterDecision('Repetições confirmadas e revisão atualizada.')}
async function correctAmount(row:GuidedPendingRow){if(await save({decisionKey:row.decisionKey,action:'CORRECT_AMOUNT',correctedAmount:rowAmounts[row.decisionKey],reasonCode:'MANUAL_BATCH_CORRECTION',justification:'Valor corrigido somente neste lote'}))await refreshAfterDecision(`Valor da linha ${row.rowNumber} corrigido e revalidado.`)}
async function correctDate(row:GuidedPendingRow){if(await save({decisionKey:row.decisionKey,action:'CORRECT_DATE',correctedDate:rowDates[row.decisionKey],reasonCode:'MANUAL_BATCH_CORRECTION',justification:'Data corrigida somente neste lote'}))await refreshAfterDecision(`Data da linha ${row.rowNumber} corrigida e revalidada.`)}
async function excludeRow(row:GuidedPendingRow){if(await save({decisionKey:row.decisionKey,action:'EXCLUDE_ROW',reasonCode:'EXCLUDED_BY_OPERATOR',justification:rowJustifications[row.decisionKey]}))await refreshAfterDecision(`Linha ${row.rowNumber} excluída deste lote com auditoria.`)}
async function excludeZeroAmountRows(decisionKey:string){if(await save({decisionKey,action:'EXCLUDE_ZERO_AMOUNT_ROWS',reasonCode:'ZERO_AMOUNT_NO_FINANCIAL_EFFECT',justification:zeroAmountJustification.value.trim()}))await refreshAfterDecision('Linhas de valor zero ignoradas neste lote com auditoria.')}
async function useDateColumn(option:{decisionKey:string;columnLabel:string}){if(await save({decisionKey:option.decisionKey,action:'USE_DATE_COLUMN',reasonCode:'ALTERNATIVE_DATE_COLUMN_REVIEWED',justification:`Coluna alternativa ${option.columnLabel} revisada somente para este lote`}))await refreshAfterDecision('Coluna de data aplicada somente a este lote e revisão atualizada.')}
async function useMonetaryFormat(saveAsProfile:boolean){const monetary=review.value?.monetaryFormat;if(!monetary?.decisionKey)return;if(await save({decisionKey:monetary.decisionKey,action:'USE_MONETARY_FORMAT',reasonCode:'DETECTED_FORMAT_REVIEWED',justification:saveAsProfile?'Formato revisado e salvo para recorrência':'Formato revisado somente para este lote',saveAsProfile})){if(saveAsProfile){message.value='Formato salvo como nova versão do padrão da fonte. A revisão será retomada automaticamente.';emit('profileUpdated')}else await refreshAfterDecision('Formato aplicado somente a este lote.')}}
async function confirmReview(){if(!review.value||!props.file||!financialConfirmation.value)return;confirming.value=true;message.value='';try{const response=await FinancialClosingService.confirmGuidedImportReview(props.closing,review.value.reviewId,props.file,review.value.revision,props.sensitiveAccessConfirmed);message.value=response.data.replayed?'Este arquivo já estava confirmado; nenhum item foi duplicado.':'Importação confirmada. Agora você pode recalcular a apuração.';review.value.alreadyConfirmed=true;review.value.readyForConfirmation=false;emit('confirmed')}catch(error:any){message.value=error?.response?.status===409?'O arquivo ou a revisão mudou. Atualize a revisão final.':'A confirmação foi bloqueada. Atualize a revisão e resolva as pendências indicadas.'}finally{confirming.value=false}}
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0)}
function participantResolutionLabel(value:string){return({LINK_PARTICIPANT:'Associado',EXTERNAL_CREDITOR:'Credor externo',PENDING:'Pendente'} as Record<string,string>)[value]||value}
function rowResolutionLabel(value:string){return({PENDING:'aguardando decisão',CORRECTED:'correção salva',EXCLUDE_ROW:'exclusão salva'} as Record<string,string>)[value]||value}
function issueLabel(value:string){const types=value.split(',');return types.map(type=>type.includes('AMOUNT')?'valor inválido':type.includes('DATE')?'data ausente ou inválida':'dado inválido').join(' e ')}
function blockerAction(reason?:string){if(!reason)return null;const normalized=reason.toLocaleLowerCase('pt-BR');if(normalized.includes('coluna que identifica o participante'))return{label:'Corrigir coluna do participante',target:'PROFILE'};if(normalized.includes('corrija a fonte ou o perfil'))return{label:'Revisar perfil da fonte',target:'PROFILE'};if(normalized.includes('beneficiár')||normalized.includes('associe todos os beneficiários')||normalized.includes('participantes da apuração'))return{label:'Revisar participantes',target:'PARTICIPANTS'};if(normalized.includes('repeti')||normalized.includes('referências repetidas'))return{label:'Revisar repetições',target:'REPETITIONS'};if(normalized.includes('valor, data ou identidade')||normalized.includes('data')||normalized.includes('valor'))return{label:'Revisar linhas',target:'PENDING_ROWS'};if(normalized.includes('formato monetário'))return{label:'Revisar formato',target:'MONETARY'};return null}
function resolveBlocker(reason?:string){const action=blockerAction(reason);if(!action)return;if(action.target==='PROFILE'){emit('editProfileRequested');return}const target=action.target==='PARTICIPANTS'?participantsSection.value:action.target==='REPETITIONS'?repetitionsSection.value:action.target==='PENDING_ROWS'?pendingRowsSection.value:monetarySection.value;if(typeof target?.scrollIntoView==='function')target.scrollIntoView({behavior:'smooth',block:'center'})}
function monetaryFormatLabel(value:NonNullable<GuidedImportReview['monetaryFormat']>){const prefix=value.format.currencyPrefix?.trim();const grouping=({DOT:'.',COMMA:',',SPACE:'espaço',NBSP:'espaço',NONE:'sem separador'} as Record<string,string>)[value.format.groupingSeparator||'NONE'];const decimal=value.decimalSeparator==='COMMA'?',':'.';return `Padrão detectado: ${prefix?`${prefix} `:''}milhar ${grouping} · decimal ${decimal}`}
watch(()=>[props.autoStart,props.profileId,props.file,props.sensitiveAccessConfirmed] as const,()=>{if(props.autoStart&&props.file&&props.profileId&&props.sensitiveAccessConfirmed)void openReview()},{immediate:true})
</script>

<style scoped>
.guided-review{margin-top:16px;padding:18px;border:1px solid #dfe3eb;border-radius:12px;background:#fbfcfe}.guided-review__heading{display:flex;justify-content:space-between;gap:12px;align-items:start}.guided-review h3,.guided-review h4{margin:2px 0 8px}.guided-review>p,.guided-review__step>p,.guided-review__message,.guided-review__warning{color:var(--cb-text-muted,#667085)}.eyebrow{margin:0;text-transform:uppercase;letter-spacing:.08em;font-size:.72rem;color:var(--cb-text-muted,#667085)}.guided-review__step{margin-top:18px;padding-top:16px;border-top:1px solid #e5e7eb}.guided-review__item{display:grid;gap:10px;margin:10px 0;padding:14px;background:white;border-radius:10px}.guided-review__item small,.guided-review__sticky small{display:block;color:var(--cb-text-muted,#667085)}.guided-review__actions,.guided-review__suggestions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.guided-review__actions :deep(.v-input){min-width:210px;flex:1}.guided-review__suggestions span{font-size:.84rem;color:var(--cb-text-muted,#667085)}.guided-review__warning{font-size:.84rem;margin:0}.guided-review__notice{margin-top:12px;padding:12px;border-left:4px solid #2563eb;background:#eff6ff}.guided-review__notice p{margin:4px 0 0}.guided-review__success{display:flex;align-items:center;gap:6px;color:#067647;background:#ecfdf3;padding:10px 12px;border-radius:8px}.guided-review__details{margin:10px 0}.guided-review__details summary{cursor:pointer;font-weight:600}.guided-review__details ul{max-height:280px;overflow:auto}.guided-review__summary dl{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.guided-review__summary dl div{padding:10px;background:white;border-radius:8px}.guided-review__summary dt{font-size:.8rem;color:var(--cb-text-muted,#667085)}.guided-review__summary dd{margin:3px 0 0;font-weight:700}.guided-review__blocks{display:grid;gap:8px;color:var(--cb-negative,#b42318)}.guided-review__blocks li{display:flex;align-items:center;justify-content:space-between;gap:12px}.guided-review__sticky{position:sticky;top:12px;z-index:4;display:flex;align-items:center;gap:12px;margin:12px 0;padding:12px 14px;border:1px solid #d0d5dd;border-radius:12px;background:rgba(255,255,255,.96);box-shadow:0 8px 24px rgba(16,24,40,.14)}.guided-review__sticky>div{flex:1}.guided-review__sticky :deep(.v-input){flex:0 1 320px}@media(max-width:700px){.guided-review__heading{flex-direction:column}.guided-review__summary dl{grid-template-columns:1fr 1fr}.guided-review__actions,.guided-review__sticky,.guided-review__blocks li{align-items:stretch;flex-direction:column}.guided-review__actions :deep(.v-input),.guided-review__sticky :deep(.v-input){width:100%}}
</style>
